### ISSUE TITLE
[FireMonkey] editor acts crazy with newlines

### ISSUE THREAD

**Issue by DerpMcDerp** [erosman/support#124]
FireMonkey does crazy things with newlines in the userscript editor:

* Sometimes it inserts spaces after newlines and sometimes not
* Sometimes it saves with spaces like "a\n b" in the export preferences JSON and sometimes with "a\nb"
* Trying to delete the space using backspace deletes the newline instead of the space
* Sometimes creating a newline breaks the line numbers in the editor (see the caret between lines 23 and 24 in this screenshot):

![firemonkey](https://user-images.githubusercontent.com/8602394/71240140-36191c00-22bd-11ea-9bd8-692436bc48ed.png)

I'm using FireMonkey in Firefox 71.0 on 32-bit Windows. Maybe this bug is because Windows uses "\r\n" and you're developing on a UNIX which uses "\n"?

Also, is there a way to make the editor use tabs instead of spaces when the tab key is pushed?

**Comment by erosman** [comment]
The Edit box is actually an editable element which also contains 1000s of other editable elements in order to display syntax highlighting.

When you enter a newline, it doesn't behaves as you expect (it actually enter the new line inside that element and does not go to the next numbered line which is another element) but once you click outside it to refresh the highlight, it gets sorted.

Comprehensive syntax highlighting libraries like CodeMirror do a better job but that involves very large libraries and many event listeners to handle the changes.

The syntax Highlighting in FireMonkey was written by me and it is comparatively basic. It is OK for some small editing but I would advise a proper editor for more than that.

> Also, is there a way to make the editor use tabs instead of spaces when the tab key is pushed?

I made the `Tab -> space` in order to make it easier to indent 1 or more lines of code. At the moment, there is no option to bypass it.

You can disable syntax highlighting and edit freely and then turn it back on.

**Comment by DerpMcDerp** [comment]
Why not just use a `<textarea>` then?

**Comment by erosman** [comment]
> Why not just use a <textarea> then?

There is no formatting/highlighting in `<textarea>`.

If you disable syntax highlighting, it will be changed to normal `<textarea>`.

**Comment by DerpMcDerp** [comment]
I found another bug: If you have syntax highlighting disabled, the editor enables syntax highlighting when it loses keyboard focus.

**Comment by erosman** [comment]
> I found another bug: If you have syntax highlighting disabled, the editor enables syntax highlighting when it loses keyboard focus.

Ooops... you are right... I will fix it and upload a new version.

**Comment by erosman** [comment]
v1.22 uploaded

**Comment by erosman** [comment]
I decided to use CodeMirror. It will be in v1.48
