### ISSUE TITLE
Firemonkey: Script streches UI

### ISSUE THREAD

**Issue by sergeevabc** [erosman/support#135]
Firefox x64 72.0.2 + Firemonkey 1.23 + [FYTE][1] script installed leads to… “where are the buttons?”

![](https://i3.imageban.ru/out/2020/01/30/e874bffa5cecb80483976b7865b4d8c6.png)

[1]: https://greasyfork.org/en/scripts/9252-fyte-fast-youtube-embedded-player

**Comment by erosman** [comment]
It does not happen to mine  (although mine is 1,24 and has some minor changes)
It should come up with error due to the Regex. Have you edited it?
If you remove the `// @icon` (not used in FM) that should help.

![firemonkey-FYTE](https://user-images.githubusercontent.com/6458876/73431763-66d98000-4356-11ea-90d8-9f87e2536a88.jpg)

**Comment by sergeevabc** [comment]
You have syntax highlighting enabled (comments in green vs gray indicate that), switch if off first.

**Comment by erosman** [comment]
You are right. I will fix it.
