### ISSUE TITLE
Error messages with arte downloader script

### ISSUE THREAD

**Issue by arnauldb** [erosman/support#136]
Hello,

I have errors when installing this script: [https://github.com/GuGuss/ARTE-7-Downloader](https://github.com/GuGuss/ARTE-7-Downloader)

![2020-02-01_19-25](https://user-images.githubusercontent.com/13196747/73597074-45c48b00-4520-11ea-9b8e-d704b01c67fd.png)

Thank you.

**Comment by erosman** [comment]
Do you mean this?
https://raw.githubusercontent.com/GuGuss/ARTE-7-Downloader/master/src/arte-downloader.js

I dont get any errors. Which version of FM are you using?

**Comment by arnauldb** [comment]
Yes, this one.
I use FM version 1.23

**Comment by erosman** [comment]
Sorry... I found the problem.. the error is set when inseting (which I didn't do).
The error is due to missing ` : `

Change `*//*.arte.tv/*` to `*://*.arte.tv/*`

**Comment by erosman** [comment]
PS. Do GM/TM/VM accept `*//*.arte.tv/*`?

I didn't it mentioned in their docs.

**Comment by erosman** [comment]
I left a note asking about the include pattern at https://github.com/GuGuss/ARTE-7-Downloader/issues/87

It works in other script manager since they convert it to RegEx but then it would also catch URLs such as:
`https://www.someothersite.com/?ref=//www.arte.tv/en/videos/072483-000-A/brexit-means-brexit/`


In any case, I have updated the code (v1.25) to convert `*//......` to `*://...... `

**Comment by arnauldb** [comment]
Thank you! I will wait for the v1.25.
