### ISSUE TITLE
Avoid overwriting current webpage when dragging *.user.js script?

### ISSUE THREAD

**Issue by pstein** [erosman/support#170]
Assume I have loaded a certain webpage into a tab of firefox.

Now I drag & drop a *.user.js script from WinExplorer onto this tab.

The script content is now displayed in this tab and the user is prompted to confirm the installation of the just dragged script. After OK the script code remains visible in tab.

Is there a way to avoid the overwriting of the the current (old) webpage content?

The script code should not (or only temporarily) overwrite the previous content.

Thank you
Peter

**Comment by erosman** [comment]
Since Firefox 57, for security, extension no longer have access to file system on user computers.

Once you drag a `*.user.js` from your computer to the Firefox, it is possible to prevent loading of the script into the tab but after that FireMonkey (or any other extensions) can not grab that file from user's file system. Therefore, there won't be a possibility to import/instal it.

Additionally, users may want to view/inspect the file that they are importing.
