### ISSUE TITLE
[FireMonkey]: JS' script compatibility question

### ISSUE THREAD

**Issue by EstherMoellman** [erosman/support#210]
Hi @erosman ! How're you?

As usual, please allow me to make you a simple question, today about JS' script compatibility.

I found this script: https://greasyfork.org/en/scripts/32626-disable-youtube-video-ads
As its name says, this script blocks YT' ads.
The Dev has a great reputation, he's is a very well known JS' Dev. He also is very active at Reddit, and helps lot of users with difficult JS' stuff.

Originally his "disable-youtube-video-ads" wasn't working at all with FireMonkey (YT' webpages were loaded partially, with lot of blank spaces). I contacted the Dev, and he kindly adapted the script to FireMonkey. And now YT' pages are fully loaded... it's a progress.
However, "disable-youtube-video-ads" + FireMonkey only works on first installation (every YT' ad is cleaned, zero YT' ads, beautiful, both "disable-youtube-video-ads" and FireMonkey work like a charm). Unfortunately, if I restart the browser, "disable-youtube-video-ads" behaves randomly, sometimes works, sometimes doesn't work (most of the time doesn't work).
The Dev can't help me anymore, because "disable-youtube-video-ads" is working well with other extensions.

From my ignorance, I can't tell you if the problem is an incompatibility between "disable-youtube-video-ads" and FireMonkey, but if it is the case, I understand, and I'm not going to request you to change FireMonkey for this "disable-youtube-video-ads", so let's forget my question and let's close this issue.
But if by chance there is something you can change in the "disable-youtube-video-ads" script, to make it compatible with FireMonkey, then please help me, I'll appreciate a lot, because I saw this JS' script working and is amazing, I really want this script working with my FireMonkey.

My friend, thank you a lot in advance, have a nice Sunday, and big hug! : )

**Comment by erosman** [comment]
> this script blocks YT' ads.

Add-ons that run in browser scope are best suited to blocks ads in comparison to scripts that run in page scope. A User-Script can never be as efficient in this regard. I use YT all the time and don't see any ads. ;)

> The Dev can't help me anymore, because "disable-youtube-video-ads" is working well with other extensions.

AFA "_workaround for FireMonkey's partial compatibility to GreaseMonkey specification_", in this case, the specifications are the same. The different is the method and scope of script injection.

I recall there were issues with other script mangers and `// @run-at      document-start` which resulted in delayed injection. FireMonkey `document-start` is to the browser standard which might be sooner than others.


Finally, the issue is not obvious and to find out exactly where it is, takes time and effort. Script developers are more familiar with their own code to be able to find it out. Understandably, they may not be concerned due to limited FM user-base.

**Comment by EstherMoellman** [comment]
Thanks @erosman  for your replay.

Yeah, I always remember one of your first teachings, about the differences between extensions and JS' scripts. But extensions are very bad against YT' ads. And JS' scripts (specifically against YT' ads) are far more lightweight and browser performance friendly.

In addition to that, and what really frustrates me, is the fact this JS' script + FireMonkey works randomly. If it is not working due to an incompatibility issue, fine, this I can accept and understand. But working randomly?... this makes me mad (LOL).

And the Dev, attending my request, already tried to adapt the script to FireMonkey... so I can't ask him for more. And you're right, Devs don't care about extensions with limited user-base. Lucky me that most of my scripts always were compatible with FireMonkey, or you helped me, or Devs helped me. At the end, I never had problems with FireMonkey.

So my friend, up to you, if from your side you can't do anything about this JS' script, then please feel free to close this issue.

Once again thank you anyway!
