### ISSUE TITLE
Evaluating FireMonkey for use in Tor Browser

### ISSUE THREAD

**Issue by Tarzan5** [erosman/support#214]
Dear developer,
Thank you for your work on this extension. I'm currently evaluating this extension for use in the Tor Browser with Javascript disabled. Tor Browser Bundle (TBB) is basically Firefox ESR tailored for anonymity. I had some questions:

1. Leaving aside the scripts and styles installed by user, does the extension itself in any way modify what content is loaded from a website or the order it is loaded in? 

    For example, TBB devs don't include uBlock extension, because different users will block different things, and the difference in web traffic patterns can distinguish them from each other.

2. If auto update is disabled, does the extension itself make network connections in the background? If so, can this be made optional? The concern of TBB devs with such extensions is that they might bypass the Tor Proxy, and communicate over clearnet.

3. What data is written to disk (other than the user script/style sheet which would contain name of the website in the metadata block). The concern TBB devs have here is forensics (where information about which websites a user uses or visits, is written to the disk).

Thanks!

**Comment by erosman** [comment]
> 1. Leaving aside the scripts and styles installed by user, does the extension itself in any way modify what content is loaded from a website or the order it is loaded in?

None whatsoever.
In other words, FireMonkey without any installed (or enabled) script/CSS, does absolutely nothing.

> 2. If auto update is disabled, does the extension itself make network connections in the background? 

None at all 
Please note that installed scripts may have remote dependencies (via `@require`) which then requires network connections in order to get them, but FM does not make any network connections for itself.

> 3. What data is written to disk (other than the user script/style sheet which would contain name of the website in the metadata block). 

FireMonkey saves it preferences to storage (via Firefox Storage API) which includes:
- General User Options/Preferences (as per Options page)
- Script/CSS that uses has added
- Data that scripts may save via `GM.setValue(key, value)`

Additionally, FireMonkey saves user **Syntax Highlight** & **Dark Mode** preference (true/false) in local storage within Firefox & only accessible to FireMonkey.

All above are saved by Firefox API and within Firefox. There is no access to user HD.

> The concern TBB devs have here is forensics (where information about which websites a user uses or visits, is written to the disk).

Just a note: Extensions will be rejected if they do that. I have been an AMO add-on reviewer myself since 2014. ;)
I wrote FM (initially for my own use) because I wanted a more secure script & CSS/Style manager. All the FM code is written by me (no imported code or library from elsewhere).

Please feel free to contact me if there are any other queries.
Please note that the minimum version requirement, as the dedicated (more secure) userScript API is only available from FF68+ (ESR Firefox 60.7)

**Comment by Tarzan5** [comment]
Thank you for the information.
