### ISSUE TITLE
Text MultiCopy: no saved data after copy to clipboard

### ISSUE THREAD

**Issue by grahamperrin** [erosman/support#24]
My first use of the extension, after reading this release note: 

>  Option to Check & Edit Saved Data

– I wondered where to find the interface. 

Eventually via about:addons I found moz-extension://406337c4-1019-4e50-a002-a532f8d2ead5/content/options.html but the **Saved data** field was blank. 

My first assumption was a bug in in the interface (always blank) but after a while, I realised that the field is populated only if I **refrain from copying**. 

So with the current design, it seems that the wording of this context menu option is misleading: 

> Copy Saved to Clipboard

– misleading because it does more than copy, it deletes what was saved. 

Maybe change the wording: 

> Move saved texts to clipboard

**Comment by erosman** [comment]
That is a possibility.

How did you find the HELP? Did it help clarify the issue?

In normal copy action on anywhere else (browser, computer, applications), text is copied to the clipboard.
Clipboard retains this text, until another text is copied. Clipboard then replaces this old text with the new one and the old one is gone. The action of getting text and populating the clipboard is universally called, **Copy**.

In Text MultiCopy, there is a new possibility to Save the text to storage and keep for later i.e. **Save Selection**

Once the user has finished with storing texts, then the user can transfer text to the clipboard i.e. **Copy Saved to Clipboard**. The transfer clears the storage, otherwise the storage will grow forever and user will be populating the clipboard with the same text repeatedly. The reason for using the work _Copy_ is as explained above, inline with the whole concept of populating the clipboard.

> – I wondered where to find the interface.

Did you check the Help? 
They are on add-on's _Option page_, accessible from _about:addons_ or via context-menu.

Saved Data means the data saved in the storage. It will show the data if there are any data in the storage. Once data is transferred out of the storage (via _Copy Saved to Clipboard_ or _Paste Saved here_), there will be nothing to show.

> Maybe change the wording:
That is a possibility and I recall one other person also made a similar comment. The word _Copy_ seems better associated with Clipboard action that _move_ or _transfer_, however, if there is a popular demand, I will change the wording.

**Comment by erosman** [comment]
OK.. I am going to change the text in the next version to make it easier.
