### ISSUE TITLE
FireMonkey: How does the new Log feature work?

### ISSUE THREAD

**Issue by CrendKing** [erosman/support#242]
FireMonkey has this one weakness, where if my script has problem in it, the error is only shown in the Browser Console, which is shared across all tabs. I remember other managers like ViolentMonkey shows error in the current tab's console. I mean I can live with it, but since you introduce the new Log feature, I was wondering how to make use of it. Apparently even though I can see the script error in Browser Console, the Log window is always empty. Is it a bug or it's for something else like only for script update?

**Comment by erosman** [comment]
> FireMonkey has this one weakness, where if my script has problem in it, the error is only shown in the Browser Console

Please read the **Help** under **Debugging Script & CSS** and also #233

Current Tab console still shows userscript operation errors since userscripts belong to a tab after it is injected.
Compile errors (when there is bad code) are shown in Browser Console since they occur when Firefox reads the script for injection and before userscript is injected. Please note that once userscript is injected, it is in the page/content scope and has no direct connection with FireMonkey anymore unless it uses one of GM_/GM. API. 

> since you introduce the new Log feature, I was wondering how to make use of it.

There were some messages that were logged to the console such as script update. With the separation of logging in Firefox, such console.log form background script appear on the debugging console i.e. 
_about:debugging#/runtime/this-firefox -> FireMonkey -. Inspect_

Above is inconvenient for most average users so I wrote the Log feature to make it easier for the users. At the moment, there are certain background errors that are logged and I will improve it further over time.

Here is an example:

![log](https://user-images.githubusercontent.com/6458876/96216712-d0092e00-0f8d-11eb-9cdc-30f432b7ba49.jpg)

**Comment by CrendKing** [comment]
Thanks. I was meant for compilation error. I'll stick with Browser Console. One thing though. In your example, it should some error about the meta block. I can't trigger those problems.

For example, I tried to do nonsense like
```
// @run-at  abc
```
or
```
// @matches 123
```
Nothing logged anywhere including Browser Console. So how do you suggest people to debug meta block related errors?

**Comment by erosman** [comment]
Compilation errors i.e. JavaScript code errors, can only be seen in **Browser Console**. I actually asked the Mozilla engineer who developed the userScript API if it was possible to catch that error, but at the moment there is no such possibility.

**Metadata Block Errors**

- Some are picked up by FireMonkey and a notice is given when trying to save the script
- Some are picked up by the Firefox API when FireMonkey attempts to register the script and that results in error in the log and also script error and red X

`// @run-at  abc` will not cause an error since FireMonkey processes Metadata Block and revert to default value (it only accepts 3 fixed values for `@run-at`)

`// @matches 123` should be picked up by FireMonkey when processing Metadata Block
BTW, you can use `@match` to be compatible with other script mangers, just in case you want to share the script.

**Comment by CrendKing** [comment]
>     * a notice is given when trying to save the script
> `// @matches 123` should be picked up by FireMonkey when processing Metadata Block

I do not see anything. Let me give you an example.
```
// ==UserScript==
// @name           Test
// @match          !@#!$!@#
// @run-at1        ~!@~#~!#@
// ==/UserScript==

(async () => {
    'use strict'

    abc
})()
```
When I save this script, no error is shown. And the popup of this script says its matches is
```
*://!@#!$!@#/
```
No error in browser console when I visit any website too.

> you can use `@match` to be compatible with other script mangers, just in case you want to share the script.

Thanks for the tip.

**Comment by erosman** [comment]
> // @run-at1        ~!@~#~!#@

No error there... Metadata Block are commented JavaScript so there is no JavaScript error.

FireMonkey looks for `@run-a       something` so  `@run-at1` will be ignored.

`// @match          !@#!$!@#` is converted by FireMonkey to a suitable format `*://!@#!$!@#/`

Although `*://!@#!$!@#/` is odd and not a real URL, it does not cause an error in [Match Pattern.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns).

```(async () => {
    'use strict'

    abc
})()
```
Above will cause a script error when it is injected in the Tab content but since nothing matches `*://!@#!$!@#/`, it is never injected to result in error.

**Comment by CrendKing** [comment]
I'm sorry I'm so bad at writing incorrect script. I usually write correct ones, so need a bit of practice :wink:.

So I went to the match pattern page and tried every one of those "invalid" patterns. These are taken as correct pattern. No error shown anywhere.
```
// @match   resource://path/
// @match   https://mozilla.org
// @match   https://*zilla.org/
// @match   http*://mozilla.org/
// @match   https://mozilla.org:80/
// @match   *://*
```
These two are shown as error. However, it is not from notification. It is in the popup where the script has a red cross:
```
// @match   https://mozilla.*.org/
// @match   file://*
```
I admit this is the first time I see error inside FireMonkey. Log still empty though.

Feel free to close the ticket.

**Comment by erosman** [comment]
> So I went to the match pattern page and tried every one of those "invalid" patterns. These are taken as correct pattern. No error shown anywhere.

FireMonkey attempts to correct **some incorrect** patterns. I wrote the conversion to help with converting `@include` to `@match`.
You can see the converted version when you try the **Info** via toolbar popup.

When it can not fix.convert bad patterns, it results in error generated by FireMonkey.

Some errors can not detected or corrected and then once the script is registered, they come up. The error is generated by Firefox API but FireMonkey log them. 

This is a example of such error from Firefox API:

> Type error for parameter userScriptOptions (Error processing matches.27: Value "*://*.example*.com/*" must either: be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/) for userScripts.register.

> These two are shown as error. However, it is not from notification. It is in the popup where the script has a red cross:

In case of error from Firefox API:
- Error is logged to the Log
- Script is disabled
- Error is logged to the file data so it can be seen as red X and a notification popups when opened in editor

**Comment by CrendKing** [comment]
> Log is not live. Log page has to be refreshed to show new entries.

You are correct. I can confirm.
