### ISSUE TITLE
Bug: since v1.46 (or v1.45) my *.user.js do not work any more

### ISSUE THREAD

**Issue by pstein** [erosman/support#256]
As I had to recognize all my *.user.js scripts do not work any more since v1.46 (or v1.45?).
They contain a lot of GM_addStyle() statements.

pls. fix this bug. I am using Firefox v82.0.2 64bit on Windows.

How can I download the previous versions v1.45 or earlier?

I cannot download it from webpage

https://addons.mozilla.org/en-US/firefox/addon/firemonkey/versions/

Thank you
Peter

**Comment by erosman** [comment]
There is a issue with 1.45 `GM_addStyle()` which is fixed in 1.46

Can you give me an example to test?

**Comment by pstein** [comment]
// ==UserScript== 
// @name            ChangeLayoutMozillazine
// @namespace       nsChangeLayoutMozillazine
// @description     Change Layout Mozillazine
// @include         http*://forums.mozillazine.org/*
// @version         1.1.0
// @grant           GM_addStyle
// @require         http://code.jquery.com/jquery-latest.js
// ==/UserScript== 

$("#gootop").remove();

GM_addStyle(".postbody .content, .post_body .content { font-size: 16px !important; }"); 
GM_addStyle(".content { line-height: 17px !important; }"); 

$("#goobot").remove();

**Comment by erosman** [comment]
You are right.. there is an issue.... fixed in 1.47
I will do some more test and upload 1.47

**Comment by erosman** [comment]
v1.47 uploaded .. let me know if there are problem

**Comment by pstein** [comment]
Seems to work. Thank you.

I changelog/history for v1.45/v1.46 you wrote about a new API.

Why was is necessary to update the API?
Was it the API of Firefox or of FireMonkey?

**Comment by erosman** [comment]
> Was it the API of Firefox or of FireMonkey?

All GM functions are API. The new ones are only in FireMonkey.

Some interface with browser (Firefox) other APIs like `GM_setValue` (saves to extension storage), `GM_setClipboard`, `GM_notification`, `GM_xmlHttpReques`t (makes the request form background to avoid page limitations) etc.

Some are **utility** API which don't use browser API and only added for convenience of the user-script developers, like `GM.addStyle/GM_addStyle`, `GM.log/GM_log`.

`GM.addStyle/GM_addStyle` only helps with the DOM manipulation and could have been done by the script. It was added by script manager to facilitate script development.
`GM.addStyle/GM_addStyle` creates a `style` element and injects into the page so the whole process can be done with one operation.

> Why was is necessary to update the API?

Like `GM_addStyle`, I created 2 more utility API to facilitate user-script development.

- `GM.addScript/GM_addScript` creates a `script` element and injects into the page so the whole process can be done with one operation.
- `GM.popup/GM_popup` creates a configurable **shadow DOM** popup that can be used for modal dialogues, script configuration,  and more. Shadow DOM is isolated from page CSS so it remains the same regardless of the page style. Script developers can do the same within the script but now instead of 170+ lines of code, they can create a popup with one operation.

There has been a lot demand over the years for  a convenient method for script configuration. Some developers made a [GM_config](https://greasyfork.org/en/scripts/28536-gm-config) user-script.
Now, in FireMonkey that can be done using the ready-made popup.
