### ISSUE TITLE
@matches example

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#278]
Could you provide an example of `@matches` directive. Any time I try to use it instead of multiple `@match`, I can't make it work.

```
// @matches      ["https://www.google.com/intl/en-GB/gmail/about/", "https://about.gitlab.com/"]
```

**Comment by erosman** [comment]
In FireMonkey `@matches = @match`.  `@matches` is an API style entry name.
They are both stored as arrays but the in metadata block they are strings.

In metadata block, in order to have compatibility with other scripts & mangers, each entry is a single string (no arrays).
These 2 are exactly the same. For better cross-compatibility, I would suggest using `@match` only   

```
// @match             https://www.google.com/intl/en-GB/gmail/about/
// @matches           https://www.google.com/intl/en-GB/gmail/about/
```
