### ISSUE TITLE
[FoxyTab] Move all tabs that match a pattern into their own window

### ISSUE THREAD

**Issue by pinacoelho** [erosman/support#290]
User story:
- I have 434 open tabs across 8 windows
- I want to pull/move all tabs that match "sendmail" into their own window.

No-Frills version:
- Caseless match of string in title & URL

This would allow people that are constantly working on several things to easily focus on one.

**Comment by erosman** [comment]
Moving by keyword is a possibility. The issue is getting the keyword.

Firefox doesn't have an independent dialogue popup. Extensions have to generate a popup from a tab page. To make it worse, It is not possible to generate a dialogue from some tabs due to them being blocked by Firefox.

Maybe sidebar can be used for that ... :thinking: 
Let's see if there is a popular demand for this feature.


_PS. Next release of the FoxyTab has selected tabs feature which would help by applying functions to selected/highlighted tab._

**Comment by erosman** [comment]
In v2.16

- Added Custom Match actions


Actions is **per window** and based on a string or Regular Expression matching of the Tab **URL**.

ATM:
- Custom Match Close
- Custom Match Reload
- Custom Match Move to New Window
