### ISSUE TITLE
[FireMonkey] [Feature request] Support features needed for RU AdList JS Fixes

### ISSUE THREAD

**Issue by shvchk** [erosman/support#306]
I've [asked](https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes/discussions/79815) [RU AdList JS Fixes user script](https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes) authors if it could work with FireMonkey, and they said that would need some features FireMonkey lacks:

> At the moment, they [FireMonkey] at least do not support the distribution [setting?] of correct access rights to objects and their properties modified by the script. As the result, Firefox blocks access from other scripts on sites to many standard APIs which my script modifies, and they breaks. Additionally, my script requires support of embedding script code before the page code runs. I haven't seen this yet in Firefox anywhere except Tampermonkey.

Would be great to have these features, so more great user scripts could work with FireMonkey.

**Comment by erosman** [comment]
Looking at details, it seems it only works or tested with TamperMonkey.

Following entries are not supported by any userscript managers
```
// @grant        GM.cookie
// @grant        window.close
```

It is a large script. If they point out exactly what and where is breaking the userscript in FireMonkey, then I can see if that is something that is possible or not.

TamperMonkey inject this script into `content` context & FireMonkey into `userscript` context but at the first glance I dont see anything that breaks it.

**Comment by lainverse** [comment]
Probably the most common issue is error: `Uncaught Error: Permission denied to access object`
As for example, you can encounter it right on the [script's page](https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes).
In this case it breaks Google Analytics code since wraps `document.createElement`. When script attempts to access `src` property of created element it fails with that error.

Another common issue is error `Uncaught Error: Permission denied to access property`.
As for example, on the same page (or pretty much any) with ABP installed it breaks APB's code injection script when it attempts to access `bind` property of `document.dispatchEvent` which my script also wraps. At least it runs before ABP.

Additionally, my script expects `GM_getValue` and `GM_setValue` to work synchronously. As the result it can't even save and load settings properly (you can open them from script commands submenu... quite inconvenient placement I'd say).

Minor issue: it seems like Code Mirror in FM fails to highlight my code properly due to template literals and large portions of my code end up highlighted as multiline strings even though they are not.

**Comment by erosman** [comment]
Thank you for detailed reply. I will liaise with Mozilla engineers and see which features can be implemented.

**Comment by pintassilgo** [comment]
I guess the permission problems can be fixed by using `exportFunction` and `cloneInto`.

For instance, in TamperMonkey or Greasemonkey you'd write something like this:

```js
unsafeWindow.setTimeout = new Proxy(setTimeout, {
    apply: function(target, thisArg, args) {
      console.log('Called setTimeout with delay ' + args[1] + 'ms');
      return target.apply(thisArg, args);
    }
});
```

But this should be used instead:
```js
unsafeWindow.setTimeout = exportFunction(new Proxy(setTimeout, {
    apply: function(target, thisArg, args) {
      console.log('Called setTimeout with delay ' + args[1] + 'ms');
      return target.apply(thisArg, args);
    }
}), unsafeWindow);
```

Even `exportFunction` and `cloneInto` being Firefox only, cross-browser extensions like TM and VM also support them. The code above works flawless also on Tampermonkey and Greasemonkey.

For Violentmonkey, things are a little more tricky: you need to replace `unsafeWindow.wrappedJSObject` instead of `unsafeWindow`.

For more info:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts#sharing_content_script_objects_with_page_scripts

**Comment by erosman** [comment]
> Minor issue: it seems like Code Mirror in FM fails to highlight my code properly due to template literals and large portions of my code end up highlighted as multiline strings even though they are not.

Fixed

**Comment by lainverse** [comment]
Ok, I see, at least at the first glance using `exportFunction` fixes permission issues. I'll update my code and we'll continue from there.

**Comment by lainverse** [comment]
I think I'm stuck:
I have definition like this in my code:
```
let Ya = new Proxy({}, {
    set(...) {...},
    get(...) {...}
});
```
Then I use `Object.defineProperty` to define `Ya` in `unsafeWindow` as pair of getter and setter. Getter returns `Ya` object (wrapped in Proxy), setter ignores whatever site attempts to rewrite this property with. Inside of `Ya` object defined multiple properties which `yandex.ru` and some other sites want to use including property `Rum` (which is also a pair of getter and setter, same as `Ya`). All getters and setter are functions exported to unsafeWindow. In TamperMonkey this works just fine (even without exporting functions), but here I get `Uncaught Error: Permission denied to access property "Rum"`.

I thought that might be related to the fact that I define `Ya` as object in my code and never clone it into `win` (`const win = (unsafeWindow || window);`). I've tried to use `cloneInto({}, win)` instead if `{}` in `new Proxy`, but then any attempt to use `Object.defineProperty` on such object crashes. Attempt to clone proxied object `cloneInto(Ya, win, {cloneFunctions: true})` before defining access to it as getter/setter pair crashes too.
`nt.define('Ya', cloneInto(Ya, win, {cloneFunctions: true}));` instead of `nt.define('Ya', Ya);`
Where `nt.define` creates that pair of getter and setter.

**Comment by pintassilgo** [comment]
It's true, `cloneFunctions: true` has no effect on FM. It works fine on VM (as I said, you need to use `unsafeWindow.wrappedJSObject` instead of just `unsafeWindow`).

I guess it's possible to fix this is FM's side.

Maybe the key is somewhere around here:
https://github.com/violentmonkey/violentmonkey/blob/63fc1ac6cc08e5f29bc1f3e189f48d384befcf7b/src/injected/web/gm-wrapper.js
https://github.com/violentmonkey/violentmonkey/blob/59b5aa4814204d08e66dfc92c4023ab79edf0178/src/background/utils/preinject.js

**Comment by erosman** [comment]
Please note some difference in the script mangers (check FM Help for more details):

- TM alters page CSP to allow script injection into page, alters `usafe-eval` to allow `eval()` ...etc
- TM with `@grant` injects into content context
- VM by default injects into page context
- GM injects into content context
- FM by default injects into userScript context
- TM `unsafeWindow = ret.window` in content context, and not available in  page context
- VM `unsafeWindow = global vm object` in content context, and `unsafeWindow = window` in page context
-  GM `unsafeWindow = window.wrappedJSObject` available in content context
-  FM `unsafeWindow = window.wrappedJSObject` available in userScript & page context

**Comment by pintassilgo** [comment]
> VM unsafeWindow = global vm object in content context

Do you know how to apply something similar to FM? I think that's what we need.

**Comment by erosman** [comment]
> Do you know how to apply something similar to FM? I think that's what we need.

It appears in VM in **content** context `unsafeWindow.window = window`

**Comment by erosman** [comment]
userScripts API strips the function when cloning (due to X-ray Vision). I am talking with the userScripts API developer in Mozilla to work something out.

ATM the result is:
```js
{
  a: 0,
  c: 2
}
```

**Comment by erosman** [comment]
Good news.... I got it working

Now I am doing more tests and if there are no problems, it will be in the next upgrade.

**Comment by pintassilgo** [comment]
I'm too curious to wait for the next update, would you mind to share your solution please? Maybe even upload your current XPI somewhere if it's easier.

**Comment by erosman** [comment]
I am wrapping `cloneInto()` into another function and then if `cloneFunctions: true` ....

```js
function cloneIntoFM(obj, target, options = {}) {
  return cloneInto(options.cloneFunctions ? obj.wrappedJSObject : obj, target, options);
}
```

Tested with ..

```js
// ==UserScript==
// @name     Test
// @match    *://*/*
// @match    file:///*
// @version  1
// @run-at   document-start
// ==/UserScript==

const win = unsafeWindow.wrappedJSObject || unsafeWindow || window;
const obj = {
  a: 0,
  b: () => console.log('Passed'),
  c: 2
};

win.exposedObj = cloneInto(obj, win, {cloneFunctions: true});
console.log(win.exposedObj);
win.exposedObj.b();

const obj2 = {
  d: 0,
  e: 'hello'
};

win.exposedObj2 = cloneInto(obj2, win);
console.log(win.exposedObj2);
```

Result
```
Object { a: 0, b: (), c: 2 }
Passed
Object { d: 0, e: "hello" }
```

**Comment by pintassilgo** [comment]
Thanks, but there may be something else, because `obj.wrappedJSObject` is `undefined`.

**Comment by erosman** [comment]
I had trouble with `class` myself when I trying to create `class popup` and had to convert it to plain `object`.

**Comment by lainverse** [comment]
@erosman Is there a place I can download and install beta-version to test with my script or you going to release new stable version soon?

**Comment by erosman** [comment]
@lainverse I will release the next update today.

**Comment by pintassilgo** [comment]
> an option would be to create the class in page context

Not possible in pages with CSP until Mozilla fixes that old bug.

But I can't imagine a single case where this would be a deal breaker. Dealing with classes is rare and I guess there are workarounds for everything, like you did by converting to `object`.

For the example I posted, the code below works and produces the exact same result even being an object instead of a class:

```js
function MyClass (x = 7) {
  win.const = cloneInto({
    x: x
  }, win, {cloneFunctions: true});
  win.const.__proto__.return_x = exportFunction(function () {return this.x;}, win);
  return win.const.__proto__;
}

win.MyClass = cloneInto(MyClass, win, {cloneFunctions: true});
```

So maybe your trick with `obj.wrappedJSObject` in `cloneInto` fixes everything. Unless the `[native code]` in `toString()` is a problem for someone...

**Comment by lainverse** [comment]
BTW, does properly cloned object remains accessible from the main script? As in can I use Object.defineProperty (with exported getter and setter) on it after it has been cloned? Can functions in it still access scopes in which they were initially created? Can I export proxied object or I have to clone object first keep proxy on the script side?

**Comment by lainverse** [comment]
Doesn't work with Proxy. Attempt to cloned proxied object crashes immediately and attempt to proxy cloned object work, but cloned functions mysteriously disappear.

```
// ==UserScript==
// @name     Test
// @match    *://*/*
// @match    file:///*
// @version  1
// @run-at   document-start
// ==/UserScript==

const win = (unsafeWindow || window);
const cloneTarget = win.wrappedJSObject || win;

const obj = {
    a: 0,
    b() { console.log('Passed') },
    c: 2
};

win.exposedObj = cloneInto(obj, cloneTarget, {cloneFunctions: true});
console.log('cloneFunctions', win.exposedObj);
win.exposedObj.b();

win.exposedObj2 = cloneInto(obj, cloneTarget);
console.log('withoutFunctions', win.exposedObj2);
!('b' in win.exposedObj2) && console.log('Passed');

try{
    win.exposedObj3 = cloneInto(new Proxy(obj, {}), cloneTarget, {cloneFunctions: true});
    console.log('cloneProxied', win.exposedObj3);
    win.exposedObj3.b();
} catch(e) {
    console.log('cloneProxied Failed', e);
}

try {
    win.exposedObj4 = new Proxy(cloneInto(obj, cloneTarget, {cloneFunctions: true}), {});
    console.log('proxyCloned', win.exposedObj4);
    win.exposedObj4.b();
} catch(e) {
    console.log('proxyCloned Failed', e);
}
```

**Comment by erosman** [comment]
@lainverse As with JS `class`, there is a issue with `cloneInto()` with `new`

You can try testing:

- create the object
- `cloneInto()` `page` context
- create a new Proxy for the cloned above object in `page` content (not proxy and clone in one operation)

**Comment by pintassilgo** [comment]
It seems that `cloneInto()` doesn't support `Proxy` just like it doesn't support `class`.

So you would need to use the old way before `Proxy` existed, with `Object` methods.

**Comment by pintassilgo** [comment]
@lainverse

Fully working:

```js
// ==UserScript==
// @name     Test
// @match    *://*/*
// @match    file:///*
// @version  1
// @run-at   document-start
// ==/UserScript==

const win = (unsafeWindow || window);
const cloneTarget = win.wrappedJSObject || win;

const obj = {
    a: 0,
    b() { console.log('Passed') },
    c: 2
};

win.exposedObj = cloneInto(obj, cloneTarget, {cloneFunctions: true});
console.log('cloneFunctions', win.exposedObj);
win.exposedObj.b();

win.exposedObj2 = cloneInto(obj, cloneTarget);
console.log('withoutFunctions', win.exposedObj2);
!('b' in win.exposedObj2) && console.log('Passed');

try{
    win.exposedObj3 = new win.Proxy(cloneInto(obj, win, {cloneFunctions: true}), new win.Object())
    console.log('cloneProxied', win.exposedObj3);
    win.exposedObj3.b();
} catch(e) {
    console.log('cloneProxied Failed', e);
}

try {
    win.exposedObj4 = new win.Proxy(cloneInto(obj, cloneTarget, {cloneFunctions: true}), new win.Object());
    console.log('proxyCloned', win.exposedObj4);
    win.exposedObj4.b();
} catch(e) {
    console.log('proxyCloned Failed', e);
}

try {
    win.o2 = cloneInto(obj, cloneTarget, {cloneFunctions: true});
    win.Object.defineProperty(win.o2, 'd', cloneInto({
        get() { return 'Passed'; },
        set() { return true; }
    }, win, {cloneFunctions: true}));
    console.log('defineProperty before clone', win.o2.d);
    console.assert(win.o2.d === 'Passed', 'accessors not cloned');
    win.Object.defineProperty(win.o2, 'e', cloneInto({
        get() { return 'Passed'; },
        set() { return true; }
    }, win, {cloneFunctions: true}));
    console.log('defineProperty after clone', win.o2.e);
} catch(e) {
    console.log('defineProperty Failed', e);
}
```

**Comment by lainverse** [comment]
@pintassilgo Not really.
1. You changed order in cloneProxied test. I might be able to avoid cloning proxied object, though.
2. You changed order in defineProperty test. I specifically tested ability to clone existing accessors there and this doesn't work.
3. You assigned object to a global variable in the window. In some cases that's something I want, but not always. I'd like to be able to keep it in a local variable in some cases.
2 and 3 means I can't define entire structure of an object before dropping it onto a page as I understand. And one of the things I use are "silently" immutable objects (objects wrapped into a proxy which ignores any changes to them, unlike frozen objects which return an error on attempt to change them).

And here's another curveball:
```
try {
    win.exposedObj4 = new win.Proxy(cloneInto(obj, cloneTarget, {cloneFunctions: true}), cloneInto({
        get(that, prop) {
            console.log('Accessed', prop, 'of', that, '=>', that[prop]);
            return that[prop];
        }
    }, cloneTarget, {cloneFunctions: true}));
    console.log('proxyCloned', win.exposedObj4);
    win.exposedObj4.b();
} catch(e) {
    console.log('proxyCloned Failed', e);
}
```
Any idea what am I doing wrong here? Because `b` ends up `undefined`.

**Comment by pintassilgo** [comment]
> You changed order in cloneProxied test. I might be able to avoid cloning proxied object, though.

I just used `Proxy(cloneInto(obj` instead of `cloneInto(Proxy(obj`, whats the difference for the variable being assigned to?

> You changed order in defineProperty test. I specifically tested ability to clone existing accessors there and this doesn't work.

You do it after, it's not hard, or am I'm missing something?

```js
// ==UserScript==
// @name     Test
// @match    *://*/*
// @match    file:///*
// @version  1
// @run-at   document-start
// ==/UserScript==

const win = (unsafeWindow || window);
const cloneTarget = win.wrappedJSObject || win;

const obj = {
    a: 0,
    b() { console.log('Passed') },
    c: 2,
    get e() {return 'Passed'},
    set e(val) {return true}
};

Object.defineProperty(obj, 'v', {
    value: 10
});

Object.defineProperty(obj, 'd', {
    get() { return 'Passed'; },
    set() { return true; }
});

win.o2 = cloneInto(obj, cloneTarget, {cloneFunctions: true});

for (let d in Object.getOwnPropertyDescriptors(obj)) {
  win.Object.defineProperty(
    win.o2,
    d,
    cloneInto(Object.getOwnPropertyDescriptor(obj, d), win, {cloneFunctions: true})
  );
}
```

I'll be back later for the rest.

**Comment by lainverse** [comment]
@pintassilgo 
> I just used Proxy(cloneInto(obj instead of cloneInto(Proxy(obj, whats the difference for the variable being assigned to?
Technically none. I can work with this.
> You do it after, it's not hard, or am I'm missing something?
As I told I'll have to completely rewrite the way I define objects on the page since right now I define structure, wrap it into a proxy which ignores further changes and define it as an accessor in the parent object which prevents ability to assign it a different value later by the page code.

I think I found less asinine way to do this. -_-
```
// ==UserScript==
// @name     Test
// @match    *://*/*
// @match    file:///*
// @version  1
// @run-at   document-start
// @grant    GM_listValues
// @grant    GM_getValue
// @grant    GM_setValue
// ==/UserScript==

const win = (unsafeWindow || window);

exportFunction(() => {
    console.log(GM.info.scriptHandler);
    console.log(GM_getValue, GM_setValue, GM_listValues);

    const obj = {
        a: 0,
        b() { console.log('Passed'); },
        c: 2
    };

    win.exposedObj = obj;
    console.log('cloneFunctions', win.exposedObj);
    win.exposedObj.b();

    win.exposedObj2 = obj;
    console.log('withoutFunctions', win.exposedObj2);
    !('b' in win.exposedObj2) && console.log('Passed');

    try{
        win.exposedObj3 = new Proxy(obj, {});
        console.log('proxy', win.exposedObj3);
        win.exposedObj3.b();
    } catch(e) {
        console.log('proxy Failed', e);
    }


    try {
        Object.defineProperty(obj, 'd', {
            get() { return 'Passed'; },
            set() { return true; }
        });
        const o2 = obj;
        console.log('defineProperty before clone', o2.d);
        console.assert(o2.d === 'Passed', 'accessors not cloned');
        Object.defineProperty(o2, 'e', {
            get() { return 'Passed'; },
            set() { return true; }
        });
        console.log('defineProperty after clone', o2.e);
    } catch(e) {
        console.log('defineProperty Failed', e);
    }
}, win)();
```

**Comment by pintassilgo** [comment]
> Any idea what am I doing wrong here? Because b ends up undefined.

Try this:

```js
try {
    aux = cloneInto(obj, cloneTarget, {cloneFunctions: true});
    win.exposedObj4 = new Proxy(aux, {
        get(that, prop) {
            console.log('Accessed', prop, 'of', that, '=>', obj[prop]);
            return obj[prop];
        }
    });
    console.log('proxyCloned', win.exposedObj4);
    win.exposedObj4.b();
} catch(e) {
    console.log('proxyCloned Failed', e);
}
```

> You assigned object to a global variable in the window. In some cases that's something I want, but not always. I'd like to be able to keep it in a local variable in some cases.

That's because you want the variable to be exposed to the page, so I expect the var to be global, but you can change this if you want:
```js
const obj = {
  b() { console.log('Passed'); },
};

let aux = cloneInto(obj, cloneTarget, {cloneFunctions: true});

console.log(aux.wrappedJSObject.b());
```

**Comment by pintassilgo** [comment]
> It is just a lot more complex way to do something that already works as-is in TM.

TM basically `eval`s the code of the userScript into the page. This turns things very simple for userScripts authors, but it's a security nightmare. For instance, you can declare just `a = GM.xmlHttpRequest` in an userScript and that's it, the page is now capable of doing cross-origin requests! There's a reason for this isolation mode to be present and default in every browser.

We also have CSP directives, allowing sites to prevent script injection from external sources, including unwanted appending of `<script>` and execution of `eval`. CSP breaks Tampermonkey world. So what to do? Well, Tampermonkey chose to disable CSP, removing that extra security layer from your users.

**Comment by lainverse** [comment]
@pintassilgo Ah, I see, so basically all objects cloned to a page end up with getter "wrappedJSObject" and I have to use it when I want to access original object's methods. And in case someone define wrappedJSObject as object's property I can do just win.Object.getOwnPropertyDescriptor(aux, 'wrappedJSObject') to access object's own property "wrappedJSObject".

So far looks fine:
```
// ==UserScript==
// @name     Test
// @match    *://*/*
// @match    file:///*
// @version  1
// @run-at   document-start
// ==/UserScript==

(() => {
    "use strict";
    console.clear();
    const win = (unsafeWindow || window);
    const unsafe = x => x && x.wrappedJSObject || x;
    const clone = (x, t = win) => cloneInto(x, unsafe(t), { cloneFunctions: true });

    const obj = {
        a: 0,
        b() { console.log('Passed'); },
        c: 2
    };

    let aux = clone(obj);
    console.log('clone in local variable', aux);
    unsafe(aux).b(); // have to be unwrapped to access methods


    win.exposedObj = clone(obj);
    console.log('cloneFunctions', win.exposedObj);
    win.exposedObj.b();

    try{
        win.exposedObj3 = new win.Proxy(clone(obj), clone({
            get(that, prop) {
                console.log('Accessed', prop, 'of', that, '=>', unsafe(that)[prop]);
                return unsafe(that)[prop];
            }
        }));
        console.log('proxy', win.exposedObj3);
        win.exposedObj3.b();
    } catch(e) {
        console.log('proxy Failed', e);
    }


    try {
        // don't defined accessors before clone
        const o2 = clone(obj);
        win.Object.defineProperty(o2, 'e', clone({
            get() { return 'Passed'; },
            set() { return true; }
        }));
        console.log('defineProperty after clone', o2);
        console.log(unsafe(o2).e);
    } catch(e) {
        console.log('defineProperty Failed', e);
    }
})();
```
The only thing I dread is necessity to rewrite half of my script to make this work. Why security and comfort almost never come hand in hand? :|

**Comment by pintassilgo** [comment]
You got it!

You just probably want to use

```js
const win = (unsafeWindow.wrappedJSObject || unsafeWindow || window);
```

to also be compatible with VM.

Thanks for your effort to achieve universal compatibility. As a FM user, an extension with less than 400 users, it's a very kind act.

**Comment by lainverse** [comment]
Unwrapping `unsafeWindow` seems like some special kind of craziness. Is this a bug in VM they have to fix or something?

**Comment by pintassilgo** [comment]
Not from devs' point of view. They are totally aware and even provided `unsafeWindow.wrappedJSObject` purposefully. That's because their `unsafeWindow` is not what it should be. At a glance, it looks that their `unsafeWindow` is the entire sandbox (global), trimmed from internals like `browser` / `chrome` and adding wrappers for dozens of native methods and globals like `scroll` and `history`. So `unsafeWindow` *looks* like it's `window`, but it's not. But it should be. `unsafeWindow` is supposed to be exactly the direct and full access to `window` as in page context.

That's the thing. VM, TM, they are all incredible extensions, but the price to be cross-browser is high. The two VM devs uses Chrome, so even being friendly to solve things for Fx it's not that optimized.

FM has incomparably smaller code than TM and VM. Besides being Firefox-only, it uses the (new) best way to deal with userScripts, the dedicated and Firefox only [userScripts API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts/Working_with_userScripts), providing simplicity, performance and security.

GM is the original one, but it almost isn't in active development any longer, and already has some major flaws. The async API in GM4 was a good thing, but the truth is that they never recovered from Fx 57 that *killed* GM3. WebExtensions' GM simply it's not on pair with the tradition of this legend extension.

FM is new and improves each day, a month ago it wouldn't even be an option for me for the lack of some essential features. It still has a lot to improve, but erosman is doing a great job.

**Comment by erosman** [comment]
> Tampermonkey chose to disable CSP, removing that extra security layer from its users.

Also from VM ...

> AFAIK Tampermonkey rewrites the CSP response header to allow its script elements. We could do it as well but it seems quite radical, I'm not even sure Mozilla will allow it in the future, they dislike addons rewriting CSP last time I heard.
> `https://github.com/violentmonkey/violentmonkey/issues/997#issuecomment-637700732`

Mozilla is looking the issue of page CSP (through multiple Bugzilla bugs), as well as extensions' behaviour.

> Unwrapping unsafeWindow seems like some special kind of craziness. Is this a bug in VM they have to fix or something? Is it specific only for cloneInto (already supported in my code) or their unsafeWindow === window?

While userscript managers are similar, there are many differences. 
VM by default tries to inject directly into `page` context if it can (i.e. there is no page CSP) and if it cant, it injects into `content` context.

> ref: https://violentmonkey.github.io/api/metadata-block/#inject-into
> ### `page` _default_
> In this mode, `unsafeWindow` refers to the `window` object, allowing the script to access JavaScript objects of the web page, just like normal page scripts can.
> 
> ### `content`
> In this mode, `unsafeWindow` refers to the global object in content script. As a result, the script can access and modify the page's DOM, but cannot access JavaScript objects of the web page.

FireMoneky **Help** has a number of comparison tables.


> you can open them from script commands submenu... quite inconvenient placement I'd say

GreaseMonkey Script Commands were originally like that too.
The UI used by TM & VM maybe preferable if there are a few userscripts. In FireMonkey, I have 140+ userscripts & userCSS and on a single page, there might be 10+ applicable userscript/userCSS. If each have a few Script Commands, you can imagine how messy the UI would get.

**Comment by pintassilgo** [comment]
> Mozilla is looking into the issue of page CSP

Did you talked to them about it? This bug is ooold, I have no expectation they will fix it soon.

**Comment by erosman** [comment]
> Did you talked to them about it? This bug is ooold, I have no expectation they will fix it soon.

Of course .... Mozilla engineers are re-working the contentScripts & userScripts API in preparation for manifest v3, as we speak.
(e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1516478#c5)

AMO review admins are also looking into extensions & CSP.

**Comment by PoetAnderson1** [comment]
@lainverse are you perhaps the author of the script?

I don't know if you were aware of this, but "Yandex Images" seems to break when using the script in "FireMonkey".

it can't get past the first [20 images](https://user-images.githubusercontent.com/85243826/124759131-b043dc80-df05-11eb-810b-2def7923a9d5.png).

clicking on "More images" doesn't seem to do anything.

at the same time... the page also breaks if you try to do a [new search](https://user-images.githubusercontent.com/85243826/124759474-0c0e6580-df06-11eb-9d2d-929ca82ec5fd.png).
