### ISSUE TITLE
Where are Firemonkey settings stored?

### ISSUE THREAD

**Issue by tobwz** [erosman/support#315]
Recently I starting a system cleaning (outside of Firefox) for all my junk, temp log and other stuff.

Accidentially I must have cleaned the settings of Firemonkey too.

After launching Firefox all my previously imported *.user.js scripts were lost and I had to re-import them.
The AddOn itself was still existing and enabled.

In order not to get this situation again I want to exclude the cleaning scope.

Where (in which folder) does Firemonkey stored its settings?
Does it store something in user.prefs or other file?

Thank you
Tobias

**Comment by erosman** [comment]
> Where (in which folder) does Firemonkey stored its settings?

Since Firefox 57, extensions don't have direct write privilege to write their data to wherever they want. All extension data storage are handled by Firefox for all extensions.
In windows, Firefox saves them in:
`C:\Users\[user]\AppData\Roaming\Mozilla\Firefox\Profiles\[profile]\storage`


It is a good idea to export FireMonkey preferences and keep it as a backup to restore everything.
