### ISSUE TITLE
[FireMonkey] [Documentation issue] Several documentation questions / clarifications

### ISSUE THREAD

**Issue by afontenot** [erosman/support#337]
1. First of all, the documentation available in the extension (under help) is really solid and complete. Thanks for that. I think it would be really nice to make it available externally on a website with separate pages for various features and so on. For example Violentmonkey has [this page](https://violentmonkey.github.io/api/gm/) dedicated to the GM.\* APIs.

2. My understanding is that in (some?) other script managers, `@grant` is actually a critical security feature, because there are certain situations in which a script running in the page might be able to get access to any APIs available to the userscript, e.g. if the script is running in page context. Is this something that applies to FM? If so, that seems like a good reason to add support for `@grant`. See https://github.com/erosman/support/issues/336

3. Any additional information that can be provided about the `userScript` context would be useful, because the documentation on MDN is unfortunately lacking. For example, I see that FM scripts have access to window / unsafeWindow. When, if ever, does using these impact security? Is `userScript` context code subject to the same CORS restrictions as the page? (In Chrome, `content` context scripts *are*, in Firefox they are *not*.) If not, is there a way to still send a request in the page context without injecting code? (Firefox provides [a way to do this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#xhr_and_fetch) for content scripts.)

4. Does using window / unsafeWindow when in `userScript` context get me access to JS objects from the page context, or does one / both of them get a window that is unique to the userScript context?

5. Typo: s/minifeid/minified

Thanks again for your hard work on this extension!

**Comment by afontenot** [comment]
Additional typos I found:

```
s/Iocn/Icon
s/configuartion/configuration
s/islolated/isolated
s/Ublock Origin/uBlock Origin
s/expresion/expression
s/proccessed/processed
s/Folowing/Following
s/to save fies/to save files
s/Fireofx/Firefox
s/permenent/permanent
s/stroage/storage
s/supproted/supported
s/Escapeing/Escaping
```

**Comment by erosman** [comment]
Thank you for your feedback.

> I think it would be really nice to make it available externally on a website

I don't have a website or domain.

> My understanding is that in (some?) other script managers, @grant is actually a critical security feature,

It used to be more important in the past when a sandbox was created by script-manager for the user-script. Since Firefox 57, other managers inject into `content` context which is sandboxed and FireMonkey into `userScript` context which is heavily sandboxed.

> I see that FM scripts have access to window / unsafeWindow. When, if ever, does using these impact security?
Support for `unsafeWindow` was added in v1.24 due to popular demand. Well-written user-scripts should not have any issue with `unsafeWindow` security and poorly-written user-scripts or malware scripts can cause issues with or without `unsafeWindow`.

:point_right:  Please note that `unsafeWindow` is not a new access channel. It is a convenient **alias** for an existing access channel. User-Scripts can access `page` context JS without it.


> e.g. if the script is running in page context. Is this something that applies to FM? 

Violentmonkey is the only script-manger that provides GM API in `page` context. (read under **inject-into** in FM help)

> Any additional information that can be provided about the userScript context would be useful,

Please read under **Xray Vision & Sharing objects with page scripts** in FM help and let me know if you have any questions.

> Is userScript context code subject to the same CORS restrictions as the page? 

Both `content` injected user-scripts (GM|TM|VM) & `userScript` injected user-scripts (FM) are subject to the page CSP and CORS, hence the need for `GM_xmlHttpRequest|GM.xmlHttpRequest` API.
ref: 
[[meta] Page CSP should not apply to content inserted by content scripts (V2 issue)](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027)
[CSP 'sandbox' directive prevents content scripts from matching, due to unique origin, breaking also browser features [Screenshots]](https://bugzilla.mozilla.org/show_bug.cgi?id=1411641)
[Websites can observe CSP violations from content scripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1588957)
[Investigate what CSP should be applied to userScripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1587494)

> is there a way to still send a request in the page context without injecting code? (Firefox provides a way to do this for content scripts.)

User-scripts can run code in page context by injecting into page context with `<script>`, using global `window` object (behaviour differs between Firefox & Chrome) (read under **unsafeWindow** & **Xray Vision & Sharing objects with page scripts** & **Injecting code into page context** in FM help).

> Does using window / unsafeWindow when in userScript context get me access to JS objects from the page context, or does one / both of them get a window that is unique to the userScript context?

The `window` in `content` & `userScript` context is not the same `window` of `page` context. `unsafeWindow` was created to access the `page` context `window`.
`unsafeWindow` gives user-scripts access to JS objects from the `page` context.

> Typo:...

Thank you for pointing them out.

# :man_facepalming:

**Comment by afontenot** [comment]
> Since Firefox 57, other managers inject into content context which is sandboxed

Last I checked, VM still injected into `page` by default, automatically switching to `content` on pages with strict CSP. I haven't looked at TM in a year or two, but it used to also inject into `page` while stripping CSP headers, making TM a security risk. Hopefully they stopped doing that. GM is the one I know always injects into a sandboxed context.

> Well-written user-scripts should not have any issue with unsafeWindow security and poorly-written user-scripts or malware scripts can cause issues with or without unsafeWindow.

I suppose what I'm asking for is any kind of information / documentation that can be provided about where the security tripwires lie. What are the current dangers that can arise from misuse of unsafeWindow / page context JS? Most discussion of this is [10 years out of date](https://groups.google.com/g/greasemonkey-dev/c/kz7NswfEOG0) at this point. It's probably unfair to put that maintenance burden on you, because you could just as easily ask the question of most other userscript managers, but FM *already* has much better documentation than any of the others, as far as I can tell.

>> Is userScript context code subject to the same CORS restrictions as the page?
>
> Both content injected user-scripts (GM|TM|VM) & userScript injected user-scripts (FM) are subject to the page CSP and CORS

This is not true. `content` scripts as injected by GM are not subject to CSP *or* CORS on Firefox. In fact, AFAIK the biggest selling point of using content scripts over the page context is that it's not subject to CSP so you can use it on strict CSP sites like Github and Twitter. Quoting from [Content Scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#xhr_and_fetch) on MDN:

> Content scripts get the same cross-domain privileges as the rest of the extension: so if the extension has requested cross-domain access for a domain using the permissions key in manifest.json, then its content scripts get access that domain as well.
>
> This is accomplished by exposing more privileged XHR and fetch instances in the content script, which has the side-effect of not setting the Origin and Referer headers like a request from the page itself would; this is often preferable to prevent the request from revealing its cross-origin nature.

I can provide a test script that uses `XMLHttpRequest` to pull a resource from a site with strict CORS, if you want to see it. Works in Greasemonkey. What I'm hoping to get added to the documentation is whether the `userScript` context behaves like the `content` context or the `page` context in this regard. Seems like an important detail.

> The window in content & userScript context is not the same window of page context. unsafeWindow was created to access the page context window. unsafeWindow gives user-scripts access to JS objects from the page context.

This is not how Violentmonkey behaves, at least. In the `content` context, unsafeWindow does *not* give you access to the page context. Quoting from [their documentation](https://violentmonkey.github.io/posts/inject-into-context/):

> The content context is an isolated world, scripts in this context have no access to JavaScript objects from page context. But they can communicate with DOM APIs such as addEventListener.
>
> unsafeWindow refers to the global object of content context.
>
> Scripts requiring access to JavaScript objects in the web page will not work in this mode. For example, unsafeWindow.jQuery becomes inaccessible even if jQuery is introduced in the page.

**Comment by erosman** [comment]
> Last I checked, VM still injected into page by default, automatically switching to content on pages with strict CSP. 

As mentioned FM Help, that is how VM does it. The point was that before FF57, user-script managers had to create a sandbox themselves and set the rules for it. Now GM|TM|VM can use `content` which is already sandboxed.
Injecting into `page` context was always a separate action and was needed on occasions to achieve certain aims. It should have been an exception to the rule, used only when necessary, but that is only my opinion.
There are security concerns with injecting into `page` context as explained in the Help.

TM injects into `page` context when @grant` is `none` & **without** GM APIs.
VM injects into `page` context be default, if it can, & **with** GM APIs.
GM only injects into `content` context.
FM injects into `userScript` context but has an `@inject-into` to inject into `page` context & **without** GM APIs.

> I haven't looked at TM in a year or two, but it used to also inject into page while stripping CSP headers, making TM a security risk. Hopefully they stopped doing that. 

TM has been doing that for the last 9 or more years and still going on. Check the FM Help for more info.
That is the reason there are many user-scripts that only work on TM.

> GM is the one I know always injects into a sandboxed context.

GM inject into sandboxed `content` context. However, the sandboxed `content` context is not as secure as sandboxed `userScript` context.

> I suppose what I'm asking for is any kind of information / documentation that can be provided about where the security tripwires lie. What are the current dangers that can arise from misuse of unsafeWindow / page context JS? 

As an example, userscripts often overwrite page functions which is not a problem.

Supposing the userscript overwrites a page function but in the overwrite, it runs functions that are in the `content` context which also has access to certain browser APIs. That could result in a situation that page JS intends to run a function on its on page but ends up running a function in the browser scope/context (not good at all).

The chance of that happing in `userScript` context is non-existent since `userScript` context doesn't have access to browser scope functions while `content` context does.

> This is not true. content scripts as injected by GM are not subject to CSP or CORS on Firefox. In fact, AFAIK the biggest selling point of using content scripts over the page context is that it's not subject to CSP so you can use it on strict CSP sites like Github and Twitter. 

That is not correct. Currently, content scripts are affected by page CSP and there are multiple Bugzilla bugs filed over it (some listed in my previous post).
The reason TM alters CSP is exactly that.
The whole point of having GM XMLHttpRequest is to bypass CORS restriction and nothing else.

> What I'm hoping to get added to the documentation is whether the userScript context behaves like the content context or the page context in this regard. Seems like an important detail.

`userScript` context is actually `content` context with additional restrictions. The base is the same, but more strict.
The other difference is the isolation. Each page has only ONE `content` context so when other managers inject multiple user-scripts, they go into the same sandboxed `content`.

On the other hand, in FM, multiple user-scripts on the same page go into multiple separate sandboxes.

> This is not how Violentmonkey behaves, at least. In the content context, unsafeWindow does not give you access to the page context.

As already mentioned in the FM help, VM behaves differently due to its implementation. However, user-script still can access the DOM window, if they want.
As mentioned before, `unsafeWindow` is a convenient alias. The access to the `window`  & page JS is available to user-scripts even without it. Therefore, it does not create any new avenue for exploitation.

Contrary to the common belief, while they all handle user-scripts, there are many differences between user-script managers.
The same can be said about browsers. While they all browse the internet but they are not exactly the same.

**Comment by afontenot** [comment]
> Supposing the userscript overwrites a page function but in the overwrite, it runs functions that are in the content context which also has access to certain browser APIs. That could result in a situation that page JS intends to run a function on its on page but ends up running a function in the browser scope/context (not good at all).
>
> The chance of that happing in userScript context is non-existent since userScript context doesn't have access to browser scope functions while content context does.

Right, but the userScript context does have access to privileged GM.\* functions. You don't want `sketchysite.biz` to be able to access `yourbankaccount.com` because a bad user script gave it access to an API function that isn't blocked by CORS. Browser APIs aren't the only thing at issue here. Is that possible with a badly written script? If so, I'd say adding `@grant` would be worthwhile.

> That is not correct. Currently, content scripts are affected by page CSP and there are multiple Bugzilla bugs filed over it (some listed in my previous post).

"Affected by" seems to be correct, yes. For example [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) says that a `<script>` tag injected by a content script should not be subject to CSP. Okay, maybe? I could see an argument either way there. My point is that if you just want to run a user script on a CSP-protected page, a `content` script *will* get you there, while a `page` script will not. If you're injecting stuff in the page that triggers CSP using that script, all bets are off, point taken. That said, I do use user scripts on strict CSP sites like Twitter and Github using Greasemonkey all the time, and they work fine. I can provide test scripts if you like.

> The whole point of having GM XMLHttpRequest is to bypass CORS restriction and nothing else.

Yes, although after Greasemonkey switched to using `content` scripts, it's now completely unnecessary. `XMLHttpRequest` in Greasemonkey bypasses CORS, because content scripts are not subject to CORS. Obviously it should be kept for compatibility with userscript managers that don't use content scripts or run on Chrome (content scripts are subject to page CORS on Chrome).

> userScript context is actually content context with additional restrictions. The base is the same, but more strict.

Thanks, that's what I wanted to know. The idea behind this bug report is to hopefully get some note about this in the documentation, as AFAIK it's hard to find information on what exactly the restrictions of the `userScript` context are. The fact that it has the exact same behavior *vis-à-vis* CSP and CORS as a `content` script is very useful information.

**Comment by erosman** [comment]
> Additional typo:

Oops .... thanks :+1: 

The issue got sidetracked and became a cross-topic issue that got partially handled in other topics.

I am going to close this topic ... but feel free to start new topics if desired.

In order to avoid sidetracking, please concentrate each topic on a single clearly defined query.
