### ISSUE TITLE
[FireMonkey][Question] Automatically uploading files

### ISSUE THREAD

**Issue by Iey4iej3** [erosman/support#355]
I wonder whether it is easy to upload the files automatically via FireMonkey scripts. A file choose looks like

``` html
<input type="file" id="docpicker"
  accept=".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document">
```

I know that modern browsers don't allow modifying this data in javascript. Even automatic clicking is not allowed without user interaction. However, I don't know whether it is doable in FireMonkey, given that it has more APIs.

**Comment by erosman** [comment]
All above are done with JavaScript so there is no need for additional FireMonkey API.

You can get JavaScript help in `discourse.mozilla.org`.

**Comment by Iey4iej3** [comment]
I would leave a final remark: I solve this by setting up a http server on the loopback `127.0.0.1`, and then call the method `GM_xmlhttpRequest` to fetch the file (otherwise there seem to be CORS issues, even if I set up the CORS to match everything on the http server), which seems to be an "additional" FireMonkey API.

**Comment by erosman** [comment]
The main point of `GM_xmlhttpRequest` in all userscript managers is the CORS since `GM_xmlhttpRequest` is sent from background script and not affected by CORS while `XMLHttpRequest` or `fetch` get the same origin as the page they are on. 

There is also a bug about the origin in userScript context (that FireMonkey uses).
ref: [scripts running using userScripts API seem to block all cross-origin requests](https://bugzilla.mozilla.org/show_bug.cgi?id=1715249)
