### ISSUE TITLE
[FireMonkey] Notify when there's error in metablock

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#384]
Currently, if I add an invalid pattern to User Matches/User Exclude Matches, when I click Save a notification pops up warning that there's an error. That's right.

But if I add an invalid matching rule to script metablock, like

    @match        *://*.example*/*

FM doesn't send a notification. You need to refresh Options page or to click FM toolbar button to realize that there's an error, because of the ❌ added next to the name of the script. The notification only pops up if you click the script in sidebar list. This notification should be displayed as soon as I saved the script after adding the error to the code.

**Comment by pintassilgo** [comment]
And text is too long, it can't be fully read in notification popup.
![image](https://user-images.githubusercontent.com/5483864/140525311-f8b96e53-ecbd-4092-a91e-e03373750b91.png)

Maybe you should switch from using notification to a display a overlay box right in the options page.

**Comment by erosman** [comment]
The error is generated by Firefox (not FireMonkey), when registering the script.

The notification comes up when displaying the script in the editor.
You can also see the error in toolbar popup and Log page.

**Comment by pintassilgo** [comment]
> The notification comes up when displaying the script in the editor.

Not if the script is already being displayed. As I said, if you're editing the script, add the wrong syntax to metablock and save the script, nothing happens as if everything is right.

**Comment by erosman** [comment]
As I mentioned, the error is generated from background script when registering the script.

- There wont be an error if script is disabled, since it wont be registered.
- The error is saved in script data, which will only show when options page is refreshed.
- The notification is only a reminder. Log is the best place to check for such errors.

**Comment by pintassilgo** [comment]
I just noticed that Log cannot be read if Options page is open in container tab. It's empty. Should I open an issue for that?

> - The notification is only a reminder. Log is the best place to check for such errors.

I suggest to trim long messages in Notification, adding something like "*Check the Log*". I know it's already said in Help that errors are registered in Log, but I still think it's user friendly to do that, because requiring everyone to read the extensive Help page is not really doable.

**Comment by erosman** [comment]
> I just noticed that Log cannot be read if Options page is open in container tab.

FireMonkey uses sync `localstorage` for some temporary/non-crucial data. The reason is to not spam extension storage with unimportant data and avoid costly async read/write.

Examples of such data are migrate version, theme, dark/light, navigation, scratchpad JS/CSS, enable/disable notice, and log & log size.

`localstorage` is isolated in normal, container & private modes.

Background scripts & popup ALAWAYS stay in normal mode. Therefore, above data are not available in container & private modes.

> I suggest to trim long messages in Notification, ...

That message is the standard Firefox match error which doesn't require reading, once you have seen it once. :wink:

**Comment by pintassilgo** [comment]
![image](https://user-images.githubusercontent.com/5483864/140551341-4631c1d8-c276-4907-923c-4d2be279ae36.png)

**Comment by erosman** [comment]
That is possible....

**Comment by pintassilgo** [comment]
> matchError > 4 && App.notify(p + '\n' + error);     // max 3 notifications

Shoudn't it be `matchError < 4`?

**Comment by erosman** [comment]
Oops... lol .. typo :man_facepalming:

**Comment by erosman** [comment]
It is done and will be in v2.35
