### ISSUE TITLE
[Firemonkey] F.B Purity userscript

### ISSUE THREAD

**Issue by Arku3S** [erosman/support#388]
Script, F.B Purity - Cleans up Facebook
The import settings option does not work in Firemonkey.
For example, in Violentmonkey it works.

**Comment by erosman** [comment]
What is F.B Purity? Where is it?

**Comment by Arku3S** [comment]
F.B Purity - Cleans up Facebook is both an extension and a script. When adding this script to Firemonkey, the import settings function failed in this script. This problem is not present in the other script manager.

Website: https://www.fbpurity.com/install.htm

**Comment by erosman** [comment]
That is a very large script (11,726 lines). The developers would need to check and if there is an incomparability, I will see what can be done.

**Comment by erosman** [comment]
Looking at https://www.fbpurity.com/install.htm

> **Install F.B. Purity - GM Script**  
> First you need to have the Greasemonkey addon for Firefox. If you don't already have it, you can get it here: Greasemonkey Once you have Greasemonkey installed and running you can install FBP by clicking the "Install F.B. Purity - GM Script" Button above.

Although the userscript states `version        33.9.5 - 2nd Dec 2021`, it seems above is outdated since the userscript uses GM3 API. Greasemonkey API changed in GM4 to asynchronous API in 2017. In other words, the script is not compatible with current GM.

Script has:
- 1 significant `GM_getValue`
- 1 significant `GM_setValue`

Therefore, it is quite easy to update it to use the new asynchronous GM API.

I have made the changes to the script. Try it and see.

[fbpurity.THRTYX.user.zip](https://github.com/erosman/support/files/7961741/fbpurity.THRTYX.user.zip)
