### ISSUE TITLE
[Copy PlainText] Error when nothing is selected.

### ISSUE THREAD

**Issue by KLszTsu** [erosman/support#405]
Copy PlainText shows an error when the keyboard shortcut is triggered but nothing is selected.

**Steps to reproduce:**

1. Make sure nothing is selected on the webpage.
2. Press the keyboard shortcut for Copy PlainText.

**What has happened:**

A notification pops up saying "There was an error with the operation".

**What should happen:**

Copy PlainText can either do nothing, or show a "Nothing selected" notification.

**Comment by erosman** [comment]
The error comes up on a number of scenarios such as no selection, inability to insert the script to get the selection due to site being blocked by Firefox or the site having restrictive CSP (Content Security Policy), etc

I thought it would be obvious to the user when they see an error and notice they haven't selected anything.

It is possible to create a separate error for each scenario if there is a popular demand for it.

_It is worth noting that another user was complaining that he/she doesn't want any notifications at all._
