### ISSUE TITLE
Firemonkey: 4chan-x incompatibility?

### ISSUE THREAD

**Issue by g-2-s** [erosman/support#408]
Hi. Here's the issue I'm experiencing: [4chan-x](https://github.com/ccd0/4chan-x) doesn't keep your settings, if you reload the page, open a thread or navigate to another board, it reverts to default and it always shows the splash screen for the settings panel like it's the first time you're using the script. What could the cause be? I seem to recall that the script used to work with Firemonkey some years ago but now it's unusable.

**Comment by erosman** [comment]
To start with, [4chan-X.user.js](https://www.4chan-x.net/builds/4chan-X.user.js) is a massive script, 1.1mb & 28, 357 lines. It would only be practical for developers to debug it.

#### Some suggestions:
- Use of `@match` instead of `@include` is a lot more robust and recommenced by all userscript managers
For example:
```
// @include      http://boards.4chan.org/*
// @include      https://boards.4chan.org/*
```
It would be better to use:
```
// @match      *://boards.4chan.org/*
```
- There are many ` @connect` and then there is a `@connect      *` which means everything so the others are not needed.


Above are only suggestions and not the cause of the incompatibility.

### Possible Cause
The possible cause of keeping/saving settings is the use of _setValue/getValue_.

The script supports both **synchronous** `GM_getValue/GM_setValue` and **asynchronous** `GM.getValue/GM.setValue`. 

- Greasemonkey only supports **asynchronous** `GM.getValue/GM.setValue`
- Violentmonkey support both but in a **synchronous** manner
- Tampermonkey support both but in a **synchronous** manner
- FireMonkey support both but `GM_getValue/GM_setValue` in an partial **synchronous** manner, and `GM.getValue/GM.setValue` in an **asynchronous** manner

Since the script is supported in asynchronous GM, it should also work in FireMonkey. However, the way script checks the supported APIs, causes issues on FM.


- Line 5277 checks for `GM.openInTab` first, so it should be fine on FM
- Line 5448 checks for `GM.deleteValue` first, so it should be fine on FM, however the next check is `GM_addValueChangeListener` (not supported by GM therefore, the script attempts the **synchronous** `GM_deleteValue` & `GM_getValue` on line 5542 which can be an issue on FM
- Line 5566 Same as above
- .... etc

Personally, I would test the supported API once at the start of the script and then use that value for the entire script.
 e.g. instead of 
```js
if (!(((typeof GM !== "undefined" && GM !== null ? GM.xmlHttpRequest : void 0) != null) || (typeof GM_xmlhttpRequest !== "undefined" && GM_xmlhttpRequest !== null))) {
...
```

I would ...
```js
// check the supported asynchronous/synchronous API
const asyncGM = typeof GM === 'object' && !!GM.info;
```

Then use `asyncGM` to test everywhere else.

### Solution
- If script developers are willing, I can make a few suggestions that should help with making the script compatible with all userscript managers
- I can add a user setting to FORCE the use of asynchronous API for userscripts that support both

:pushpin: I am going to add the feature anyway. It will be there for the next upgrade.

**Comment by g-2-s** [comment]
Yeah, I opened an [issue](https://github.com/ccd0/4chan-x/issues/2908) exactly 1 year ago on the 4chan-x repo but never got a reply, so I think it's safe to assume the dev is not going to bother with compatibility with other userscript managers. If you can manage to update Firemonkey so that the script can work as intended (which it does actually, it only doesn't save your prefs), I'll forever be grateful and hopefully some other anons will too.

**Comment by erosman** [comment]
`@disable-synchGM` added to **User Metadata** in v2.41
It will remove all `GM_*` API support so userscripts that use both types will be forced to use `GM.*` API.

> If you can manage to update Firemonkey so that the script can work as intended

If the problem is the sync/async checks, and the userscript work fine on Greasemonkey, then hopefully that will solve the issue. Let's see.

Note: I have added support for containers (#378) in v2.41
- Container in userCSS is done for Firefox 97 in [Bug 1470651 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1470651)
- Container in userScript is not done yet in [Bug 1738567](https://bugzilla.mozilla.org/show_bug.cgi?id=1738567)

I am waiting for above to release v2.41

**Comment by erosman** [comment]
v2.41 uploaded

Try `@disable-synchGM` in **User Metadata** and see if that helps

**Comment by g-2-s** [comment]
Hi sorry for the late reply but 2.41 + @disable-synchGM now make the script finally save your prefs, thank you very much for this!

**Comment by erosman** [comment]
Also in v2.42
Added experimental background `@grant` processing to disable sync GM API if both sync/async GM API are supported

**Comment by erosman** [comment]
Above feature may make the `@disable-synchGM` obsolete :thinking:

**Comment by erosman** [comment]
re: #507

@g-2-s Are you having issues with [4chan-x](https://github.com/ccd0/4chan-x)?

**Comment by g-2-s** [comment]
> re: #507
> 
> @g-2-s Are you having issues with [4chan-x](https://github.com/ccd0/4chan-x)?

Yeah, unfortunately the 4chan-x script doesn't work at all with Firemonkey.

**Comment by qwertea** [comment]
The script doesn't work at all unless I manually "run" it from the FireMonkey popup.
