### ISSUE TITLE
[FireMonkey] Full source code is missing

### ISSUE THREAD

**Issue by theAkito** [erosman/support#415]
I stumbled upon this extension, when comparing userscript runners. Everywhere it says, it's open source, etc. But where is the source? All I could find is some `zip` files in the Releases section of this repository. However, that's not the full source code, as it's missing VCS changes, etc.

So, where is the open source repository of FireMonkey?

**Comment by erosman** [comment]
> [What is open source software?](https://opensource.com/resources/what-open-source)
> Open source software is software with source code that anyone can inspect, modify, and enhance.

FireMonkey source is available by opening the XPI. It's code is clear, and not obfuscated or minified.
Open source software definition does not mean or require a Github (or similar) repository. My software development process does not use repositories and/or Pull Requests.

FireMonkey is released under [Mozilla Public License 2.0](http://www.mozilla.org/MPL/2.0/) licence which is an [open source licence](https://opensource.org/licenses).

The [FireMonkey repository](https://github.com/erosman/support/tree/FireMonkey) was created as _"Main FireMonkey JavaScript files (not including libraries) **for reference and discussion**"_.

Changes can be viewed for each above release e.g. https://github.com/erosman/support/commit/17774dc4048f9000f77677b024ec531c97c872fb

Changes to library files such as CodeMirror or jQuery etc can be viewed in their respective original releases.

**Comment by boehs** [comment]
But why?

**Comment by JJRcop** [comment]
> But why?

I think you should clarify what you are asking, because this question as-is can be answered with what @erosman wrote earlier:

> My software development process does not use repositories and/or Pull Requests.

**Comment by adamency** [comment]
@JJRcop Your quote of @erosman is precisely what the "why ?" of @boehs is referring to.

Not showing the repository is in and of itself obfuscation, whether it is voluntary or not, as we lose commit messages, evolution (i.e. commits) between two contiguous releases, history statistics, contributors, and many other important aspects of open source software.

Of course, as mozilla extensions are actually simply source code in zip files, one can inspect the source code of any extension, but it is disingenuous to get behind this straw man argument: 

- First, this argument can be used for every single firefox extension in existence, and this is absolutely fallacious as the vast majority of them are actually simple wrappers on locked and close-source software.
- Secondly, this greatly impairs visibility and inspection to the community as the repository history is mostly hidden, and the only one left (i.e. the different releases) must be reconstructed manually and can even be lost with time. 
- Third, and the most important one, the vast majority of people aren't aware of this at all, as is shown by these kind of posts and the author perfectly knows what is addressed in this post.

So all in all, this makes malicious behavior prevention far more complicated to prevent by the community than with an public repository online like most open-source projects. And this is all the more problematic given the nature of this extension which is designed to run any kind of javascript script on users' browser.

Now of course the author could be honest in saying they don't use a repository even if this is a bit hard to believe since their very "support platform" for all these extensions is literally a dummy github repository and that they have other repositories on this platform. And lastly given the content of the project that I have vetted quite in depth, it would be very surprising that the author doesn't have any mean of version control for it, besides Mozilla extension de facto hosting. BUT this **is** possible, and and as they are technically kindly sharing this open-source code free of charge, they are not obligated to anything.

**However, given all the reasons I mentioned above, I still maintain the importance and even necessity of easy code visibility and analysis for such software.**

**Which is why I made a git repository of the project** myself in order to get all the insights `git` and by extension github provides in order to better understand the project. It is **available at https://github.com/adamency/firemonkey.**

I could only retrieve the last 25 versions, so the history before 2022-28-02 is lost unfortunately unless @erosman is willing to share the history in the future.

I intend on keeping it updated for each version. Hope this will be useful to some people.

**Comment by JJRcop** [comment]
> Your quote of @erosman is precisely what the "why ?" of @boehs is referring to.

Hey! I was just noting that the question of "But why?" requires a lot of inference and can easily be misinterpreted whether by accident or on purpose, and one of those "misinterpretations", namely "But why is the source code missing?" is already answered by the quote I referenced. I was hoping to see someone ask directly "Why don't you use repositories?" which is a much clearer and more direct question, but not one I wished to ask myself as I don't actually care.

I don't feel the need to disagree with your other points and I appreciate that you have decided to maintain a repository for the convenience of everyone, thanks!

**Comment by boehs** [comment]
To clarify, the comment I left a year ago was asking why not have a public source tree even if contributions are not accepted. I thought that would be clear.

**Comment by JJRcop** [comment]
> I thought that would be clear.

With appropriate context and **GOOD FAITH** (this is key), it is clear yes. To defend against bad faith, be more detailed! :smile: 

That is essentially why I made my comment

**Comment by MestreLion** [comment]
After reading many issues requesting the source code, such as #97, #110 and #234, I want to say I'm very glad to find out you've been publishing the code under the [experimental branch `FireMonkey`](https://github.com/erosman/support/tree/FireMonkey)!

I understand you had to install and learn new software and add additional steps to your workflow, so I truly appreciate your effort!

As for how important this is for the community, and trying to address some of the points you mentioned in those threads, here are some thoughts:

- About why your most popular, firefox-recommended extensions with a lot more users don't get the same requests as FireMonkey, it might have to do with the user base. Being a userscript extension it surely has more programmers and developers among its users than other extensions, and those are more familiar with and somewhat expect FOSS projects to use this workflow.

- Other similar extensions with minified or even proprietary code may have a lot more users simply because no better alternatives existed. And I'm sure they would get similar requests and complains if they had set up a proper communication channel like you did. The fact so many people came _here_ is possibly because they're considering FireMonkey as their preferred solution, are these are major points in their evaluation.

- As you probably have figured out by now, Github, the hosting platform, is not `git`, the version control software. You can still develop locally, like you always did, using your favorite editor, without ever navigating  to https://github.com. You just _push_ the code from your machine so it gets published here, as if github was nothing more than a cloud drive. It _can_ be much more than that, but it doesn't _have_ to.

Nowadays, most successful projects use a similar methodology, to publish releases in a standard source repository under version control with a FOSS license. It makes inspecting the code and fixing bugs a lot easier, if enables all sorts of automation and transparency, it lowers the risk of a project being abandoned or hijacked.

So the effort you had are important steps towards the currently established software best practices. It has enormous benefits to everyone, and speaks a ton about the maturity of the project and about you as a developer.

Welcome to git, to FOSS, to the community. Hope you have tons of fun in this ride!

**Comment by adamency** [comment]
@MestreLion did you even look at their profile for 5 seconds ? erosman has had this github account for at least 10 years, with hundreds of contributions a year, whether commits, issues and even merging pull requests as we can see in the history of the branch you mentioned. They perfectly know about git and the difference with github, and that for many years, far before this present issue was made.

However, I gotta say @erosman thank you indeed for providing the source in that other branch. I still don't understand why hiding it like that, but whatever, I've made my peace with this.

**Comment by MestreLion** [comment]
@adamency I didn't mean to sound patronizing, and I apologize if it did. The idea was to congratulate and thank for his efforts with this frequent user request.

And despite his account being 10 years old, it seems that circa 2019-2021 he still wasn't using `git` locally, and was very reluctant to incorporate it to his workflow, at least judging from the his comments in this topic and the others I mentioned. It is still very unconventional to not have _source_ repositories for his projects, and to merge issues from all extensions in a single, codeless support repository. This unconventional structure was possibly the reason you created and still maintain your [adamency/firemonkey](https://github.com/adamency/firemonkey) repository 2 years ago.

Yes, a lot could have changed in the last 2-3 years, so I apologize if my speech is outdated, but I believe a "thank you" was still warranted. Not only for him but for you too. Creating that repository was an amazing initiative!

**Comment by adamency** [comment]
> The FireMonkey branch was added due to the requests made here.

@erosman My sincere thanks for this, the background explanation and for your work as a whole :)
