### ISSUE TITLE
Many incompatibilities unfortunately

### ISSUE THREAD

**Issue by ale82to** [erosman/support#441]
first of all I wanted to thank the dev of this promising extension anyway I ve found lots of incompatibilities coming from violentmonkey :for example this UserScript :
https://greasyfork.org/it/scripts/18671-inject2download
prevent some pages from even loading when enabled !

or this one (I write it myself )
https://gist.github.com/ale82to/78413a543edb251d33577ca3cdb1c137
is not preloading pages (to be fair this one only works in violentmonkey even in tampermonkey is not working ).
even this script on mobile gives lots of error :
https://greasyfork.org/it/scripts/375806-%E6%89%8B%E6%9C%BA%E7%AB%AF%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8A%9F%E8%83%BD%E6%89%A9%E5%B1%95

**Comment by erosman** [comment]
After a very quick glance at the code ....

### [Inject2Download](https://greasyfork.org/it/scripts/18671-inject2download)
I didn't see any issues but it is too large to debug.
VM by default injects into `page` context and TM injects into `page` context when `@grant        none`.

You can try `@inject-into page` in FM **User Metadata** and see.


### https://gist.github.com/ale82to/78413a543edb251d33577ca3cdb1c137

`@inject-into content`
That is VM only. FM only supports `page`.

```js
// @run-at   document-start
// ==/UserScript==
(function(){
window.addEventListener('load', function(){
```
There is no point in `document-start` and then wait for the page to load (but it is not a problem).
It is the same as `document-idle`.

There is no need to wrap the code in 2 functions (but it is not a problem).
```js
(function(){
  window.addEventListener('load', function(){
  
  }
  })
})()
```

I didn't see any issues. If you point out where the issue is, I can see what can be done about it.


### [Mobile browser function expansion](https://greasyfork.org/en/scripts/375806-%E6%89%8B%E6%9C%BA%E7%AB%AF%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8A%9F%E8%83%BD%E6%89%A9%E5%B1%95)

If above only works in VM and not in TM, then it is possible that VM injects it into `page` context (default VM behaviour).

VM is the only userscript manager that supports GM functions in `page` context. (Read FireMonkey **Help** under **Context Comparison**)
