### ISSUE TITLE
[FoxyTab] After the latest update, an option to move the current tab to end/start of the current window is missing

### ISSUE THREAD

**Issue by hgdagon** [erosman/support#466]
There used to be an option to move the current tab to the very end or the start of the current window. After the update, that option is missing.

**Comment by erosman** [comment]
If you check _About -> Changelog -> 2.16_
- Removed "Move Tab to Start/End" of tabs as it is built-in since Firefox 68

Since Firefox already has the menu, there was no point in duplicating it.

![move-to](https://user-images.githubusercontent.com/6458876/165300829-d42e32ac-0510-4193-975b-cb665d19f11b.jpg)

**Comment by hgdagon** [comment]
You are correct. I am blind, apparently. Never actually noticed it.
