### ISSUE TITLE
Can't update/install Foxytab 2.28 (Windows)

### ISSUE THREAD

**Issue by MintMain21** [erosman/support#476]
The update went perfectly fine on Linux, but on Windows It just wouldn't update. I uninstalled thinking a reinstall would fix the problem, but now it won't even install.

**Comment by MintMain21** [comment]
Never Mind. I uninstalled it in Troubleshooting mode then reinstalled it.

**Comment by erosman** [comment]
I am on Nightly which updates twice a day. It does happen that after an upgrade, extensions don't behave as they should. Shutting Firefox down and starting it again often fixes it.

I am guessing it is due to heavy cacheing that the Firefox does.

On occasions, restarting Firefox in Troubleshooting mode and then restarting it again in normal mode (without doing anything else) would also clear cache related issues.
