### ISSUE TITLE
[FireMonkey] Auto-Update does not work on "private" script (whitelist option?)

### ISSUE THREAD

**Issue by FinalDoom** [erosman/support#480]
Installing a script from my website works, but Auto-Update is deselected. Trying to select it displays a notification "Script/CSS does not have updateURL or version". I use my website for personal scripts that I don't want to publish or that aren't for other people, on rare occasion.

It seems like github, greasyfork, etc. must be whitelisted (haven't taken a look at the xpi source), because installing from those sources without updateURL/downloadURL works and allows Auto-Update. My scripts have @version, but neither update or download URL.

There is a workaround to this, if I edit the script to a lower version, and add a update or download url meta, save, then I can click Auto-Update. And on asking for update, it downloads the "new" (current) version, which doesn't have download/update url, and Auto-Update continues to be selectable, indicating that FM stored that URL for the script.

This leads me to assume there must be a "safe sources" whitelist (also saw a mention in issues of raw.github.com/\*/\*/\*.user.js). Can an option added to allow customizing it? Or maybe this is just a bug I've found, and any source should be setting its update/download URL like other monkeys do?

Edit: This also seems to affect scripts on gitlab. (I'm trying to import everything from tampermonkey today) If this is a whitelist thing, not so much a bug, perhaps the whitelist can be applied in a different manner, like warning users when installing from an "untrusted" source, but still recording the install source either way (trumped by in-script download/update url)

**Comment by erosman** [comment]
> Trying to select it displays a notification "Script/CSS does not have updateURL or version".

`@Version` is invalid. It should be `@version`.
You should see a warning in the editor about it.

![version-error](https://user-images.githubusercontent.com/6458876/168873122-7a629deb-0e3d-4d70-8d62-c566f92a0706.jpg)


You can set any `@updateURL` that you want and as long as it leads to the actual text of the script, it will be updated.

If you paste the metadata block, I can see if there are any problems.

There is no whitelist/blacklist for the `@updateURL`. There are a few sites like github, greasyfork that if you download from, and the script doesn't have a `@updateURL`, then the URL you downloaded it from will be set as the `@updateURL`. That is all.

**Comment by FinalDoom** [comment]
Pretty sure github capitalized the @version as a user. It's correct in the metadata.

You've pointed out the behavior in question. So my suggestion is, since repos other than raw.githubusercontent.com, et. al. exist, **can we add to that list?** Notably gitlab is not on there, where some people host scripts in lieu of github's nebulous behavior on some issues. My scripts are on the public internet, but I'm not comfortable posting their URLs. 

The question, beyond the above request, is why is this behavior not universal in FM as it is in other script managers. Why is there a url filter at all?

**Comment by erosman** [comment]
> The question, beyond the above request, is why is this behavior not universal in FM as it is in other script managers. Why is there a url filter at all? I can install from anywhere, which matches other monkeys, but the update behavior is inexplicably inconsistent.

Their documentations states the requirement for `@updateURL` (or `@downloadURL`).

- Tampermonkey [@updateURL](https://www.tampermonkey.net/documentation.php#_updateURL)
- Violentmonkey [@downloadURL](https://violentmonkey.github.io/api/metadata-block/#downloadurl)
- Greasemonkey [User Script Hosting](https://wiki.greasespot.net/User_Script_Hosting)

Greasyfork opted to remove these from posted userscripts to force updates from greasyfork.

> [Script meta keys read by Greasy Fork](https://greasyfork.org/en/help/meta-keys)
> 
> [@updateURL,](https://greasyfork.org/en/help/meta-keys#meta-updateURL) `@installURL`, `@downloadURL`
> - Describe how user script managers should get updates. Greasy Fork will strip these keys, which makes any script installed from Greasy Fork only update from Greasy Fork.

The behaviour of manually adding greasyfork as `@updateURL` is according to the requirements by GreasyFork. 

> You've pointed out the behavior in question. So my suggestion is, since repos other than raw.githubusercontent.com, et. al. exist, can we add to that list of "a few sites"? 

Most server may not appreciate being the target of auto-update as it creates extra load. Greasyfork & OpenUserJS prohibit using the actual script URL e.g. `*.user.js` and require the use of meta e.g. `*.meta.js` to check for updates in order to reduce any unwanted load. There are many userscripts that are over 2+ MB. Auto-update checks would mean considerable unwanted load if there are many users (especially with a short Auto-Update Interval).

Including, or not including `@updateURL` is the choice of the developers. Developers may have intentionally decided not to include the `@updateURL` as they did not want to have their repo become the target of the auto-update process (and complications that comes with it).


> This appears to be done in the backend and hidden from the user, as it's not on the installed script text, at least on a couple I have from github. This again leads me to the question of why those specific sites have this behavior and not all.

Please note that there is a considerable risk with arbitrarily setting any downloaded location as the `@updateURL`. A script posted to some location may look fine but can change to a malware with the next update. FireMonkey prioritises security.


**Finally**, considering the documentations of userscript managers, doesn't setting `@updateURL` as the downloaded location go against the developer's wishes? :thinking: 

:pushpin:  _PS. Gitlab is not as open as Github, since they actively block access from users of whole countries (politically motivated)._

**Comment by FinalDoom** [comment]
The behavior in tampermonkey, in my experience, doesn't require a url to be specified. This seems to match the documentation, though the documentation isn't exactly clear. Only in the case where "none" is specified will it disable updates.

As for developers' wishes, I personally prefer not listing the URLs as it decouples the script from where it's hosted--ie. I don't have to change the script when I change webservers. Additionally it doesn't result in my "private" site being written down in places.

> Please note that there is a considerable risk with arbitrarily setting any downloaded location as the @updateURL.

As has been discussed elsewhere, this is the case for any source. Why is that risk being ignored for the sites you've listed? Why not make this whitelisted set of URLs visible and customizable? Or even make it empty, with a suggestion to add those you've listed? That would be even more secure.

**Comment by erosman** [comment]
Let me see what the best approach would be. :thinking:

**Comment by erosman** [comment]
GM|TM|VM set the downloaded location as the auto-update target if `@updateURL` or `@downloadURL` is missing from the metadata block.


FireMonkey currently only does that for a limited URLs that are known as userscript/userCSS/userStyle repositories:
```
'https://greasyfork.org/scripts/',
'https://sleazyfork.org/scripts/',
'https://openuserjs.org/install/',
'https://userstyles.org/styles/',
'https://userstyles.world/api/style/',
'https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/',
'https://raw.githubusercontent.com/',
```


Options are:
- Continue as it is
- Add more sites to the above
- Add any site as the auto-update target
- Create a allowed list preference in the FM options 
- Add option to set `@updateURL` as User Metadata

Last one should be a good option. :thinking:

**Comment by FinalDoom** [comment]
If I'm understanding the nomenclature correctly, having updateURL in User Metadata means it would show up in the right side dropdown, above script storage (GM_set/get)? If so, I like this idea a lot. It offers visibility that no other script manager seems to have into _where_ updates are coming from, is auditable, etc.

Aside question RE .meta.js and such. I saw a couple tickets referencing them and that FM pulls .user.js not .meta. Does it now pull meta and fall back to .user.js? It should be fairly straightforward for people who care on github to use github actions to build meta on commit. Might be something I'll poke around at if FM does use meta.

**Comment by erosman** [comment]
> If I'm understanding the nomenclature correctly, having updateURL in User Metadata means it would show up in the right side dropdown, above script storage (GM_set/get)? 

Indeed .... User Metadata is a place for user to set persistent changes to script metadata block

> Aside question RE .meta.js and such. I saw a couple tickets referencing them and that FM pulls .user.js not .meta. Does it now pull meta and fall back to .user.js?

`greasyfork.org/sleazyfork.org` & `openuserjs.org` supply `.meta.js`. Userscript managers can change the URL and get `.meta.js`.
FireMonkey queries `.meta.js` for above in update check first and then if it has a higher version, FM fetches the actual userscript.

Example:
```
 https://greasyfork.org/scripts/424574/code/424574.user.js
 https://greasyfork.org/scripts/424574/code/424574.meta.js
```

AFA github and other locations, since they don't provide `.meta.js`, then the actual script is queried and if the version is higher, it is updated.

- The  `.meta.js` would mean getting a small file first and if needed getting the script, i.e. 2 HTTP requests.
- The other would mean getting the script directly, 1 HTTP request but often wasted if there is no need to update.


In the early days (`userscripts.org`), these 2 were required to be listed in the metadata block e.g.
```
// ==UserScript==
// @name
// @namespace    
// @description
// @updateURL     https://userscripts.org/scripts/source/12345.meta.js
// @downloadURL   https://userscripts.org/scripts/source/12345.user.js
// @include
// @author       
// @version       1.0
// ==/UserScript==
```

After the closure of `userscripts.org` and the start of GreasyFork, these were dropped.

**Violentmonkey** only uses `@downloadURL`
> [@downloadURL](https://violentmonkey.github.io/api/metadata-block/#downloadurl)
> The URL the script can be downloaded from. Checked for updates automatically at a regular interval, and also manually on user request. Automatically added when using "Install from URL."

**Tampermonkey** uses `@updateURL` for update check and `@downloadURL` for downloading

> [@updateURL](https://www.tampermonkey.net/documentation.php#_updateURL)
> `@updateURL`
> An update URL for the userscript.
> 
> `@downloadURL`
> Defines the URL where the script will be downloaded from when an update was detected. 

**Greasemonkey** doesn't support above declarations

> [Auto-Update Scripts](https://github.com/greasemonkey/greasemonkey/issues/3057)
> downloadurl and updateurl are not honored in greasemonkey. The script will be updated from the location that it is installed from. If it is installed from greasyfork then the updater will look at the original download link from greasyfork.

As it can be seen, the implementation is not uniform.

> Might be something I'll poke around at if FM does use meta.

ATM, FM doesnt have a process to look for `.meta.js` from other sites.

**Comment by erosman** [comment]
v2.57 Removed allowed install URL checklist

Install URL will be set as update URL if there is no `@updateURL` in the metadata block.
