### ISSUE TITLE
[FireMonkey] Type error for parameter userScriptOptions

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#49]
This script gives the error: https://greasyfork.org/en/scripts/6325-pinterest-without-registration.
Doesn't like something about this line
`// @include     https://*.pinterest.*/*`
but I don't understand what's wrong with it.
Violentmonkey does not complain. Didn't test with other *monkeys as I'm not using them.

Firefox 65.0.1 (64-bit) on Linux Debian Testing.

**Comment by erosman** [comment]
The Firefox match Mathern API doesn't accept `https://*.pinterest.*/*` and in FireMonkey I have adhered to the Firefox API.

Other script managers insert script in a different way (not using the secure userScript API).

If you are using a fixed TLD for **pinterest**, then I suggest changing it to that one

for example:
`// @include https://*.pinterest.com/*`

In fact that script already has that.

The script has added `// @include https://*.pinterest.*/*` to cater for other pinterest TLDs (if there are any)

You can delete that line in FireMonkey

eg:
```

// ==UserScript==
// @name        Pinterest without registration
// @namespace   http://andrealazzarotto.com/
// @version     2.2
// @description Allows to browse Pinterest without login/registration, removing the offending modal popup
// @include     http://*.pinterest.com/*
// @include     https://*.pinterest.com/*
// @copyright   2014+, Andrea Lazzarotto
// @require     http://code.jquery.com/jquery-latest.min.js
// @license     GPL version 3 or any later version; http://www.gnu.org/copyleft/gpl.html
// @grant       GM_addStyle
// ==/UserScript==


```

**Comment by rubaboo** [comment]
Ok, I get it. Is this the relevant documentation, [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#host)?

**Comment by erosman** [comment]
It is explained here: [Invalid match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#Invalid_match_patterns)

`https://mozilla.*.org/                  "*" in host must be at the start.`

**Comment by rubaboo** [comment]
Still, there needs to be a solution for covering different TLDs. [These](https://bugzilla.mozilla.org/show_bug.cgi?id=1437098) [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1315558) touch on it. [Here](https://github.com/gorhill/publicsuffixlist.js) is how uBlock Origin deals with it.

**Comment by erosman** [comment]
I also filled [TLD in Match patterns in Permissions](https://bugzilla.mozilla.org/show_bug.cgi?id=1362849) but it was not approved.

The logic in Match Pattern implementation in Google Chrome (copied in Firefox) complicates the matter otherwise I would have crated a workaround.

It is possible to use Globs but that would only work in certain situations and the include must be a catch-all pattern. TBH, I would have implemented the match pattern logic differently (already discussed with the engineers) but that ship has sailed long ago and there is no possibly of any change.

[Chrome extension: Run on all google domains and a specific page](https://stackoverflow.com/questions/18613731/chrome-extension-run-on-all-google-domains-and-a-specific-page)

**Comment by rubaboo** [comment]
Seems to me Mozilla initiated [The Public Suffix List](https://publicsuffix.org/) exactly because a TLD cannot be expressed by a pattern, and must be determined by a lookup. Hence Match Patterns do not apply.

**Comment by erosman** [comment]
v1.25
Added TLD wildcard for <code>@matches</code>
