### ISSUE TITLE
[FoxyTab] Mark to indicate the selected reload interval

### ISSUE THREAD

**Issue by guzszisvww** [erosman/support#53]
Hello.

1. Would you add a mark to a menu item to indicate the selected reload interval, please?
2. Would you add a small clock icon in a favicon to indicate that the tab is auto-reloaded, please?

![foxytab-enha](https://user-images.githubusercontent.com/48548398/55064339-b9307d00-5071-11e9-8995-a0fb86d3d018.png)

Thank you.

**Comment by erosman** [comment]
I will work on it on the next upgrade.
The favicon might be troublesome as it is set in page content and FoxyTab doesn't touch page at all.

**Comment by erosman** [comment]
I am working on this for v2.16

- Adding marker in the context-menu does not work since the marker would be global for all context-menus of all tabs
- Adding an icon to tab tile is possible but it is lost after reload
- It is possible to add extra listeners to mark the tab after reload but that is extra resources for very occasional use

**Comment by erosman** [comment]
Finally, I added the listener for now. Lets see how it works out with users.
