### ISSUE TITLE
[Replace 1.1.] Find Pattern not found (scanning "widget content")

### ISSUE THREAD

**Issue by CleverMuse** [erosman/support#6]
Hello again,

When I try to _Find_ and _Replace_ values inside a UI window I receive the error: _Find Pattern not found_ 

This UI window doesn't open like a browser window pop-up, but opens within the webpage, probably using javascript. Below is the link of a button I click to open this modal window to edit a form in my online application:

`<a id="F1_HYPERLINK_0" tabindex="9" class="btn btn-primary pull-right" rel="tooltip" onclick="OpenNewWindow('dynamiceditmodal.aspx?FormKey=4796e217-c4bf-4df9-bb00-4e2a54bbfa1a&amp;key=a33045f3-3231-4547-9c5a-780a12c61c55');bConfirmNavAway=0;" href="javascript:void(0)" style="" data-original-title="edit template">Edit</a>`

Below is an image of the view source with the behavior of this window as I click on the button to open it. It appears that every time I click that button while I'm on the page a div is added to the bottom of the web page just before the body tag. You can see the last one highlighted and as I click/close/click it just keeps adding ("ui-id-7", seventh click).

![image](https://user-images.githubusercontent.com/43575829/46020084-8221e480-c0ab-11e8-9176-a9c2928774c6.png)

If this helps, the web browser's _Find_ (Ctrl+F) will scan and recognize this area. Any idea if there is a way for the extension to recognize this area too? 

I understand you offer this for free, but most of the work I do that may require this _Replace_ tool would operate in these windows, so any help is appreciated. 

Thank you,
Dan

**Comment by erosman** [comment]
I would need an example page to see what is happening and to test it.

**Comment by DanielTomberlin** [comment]
Since the application is behind a secure login, I'm limited to pasting code and providing images. 

I don't know anything about extensions, but I hoped the fact that FireFox's _Find_ (Ctrl+F) scans this area would help troubleshoot, along with the provided. If you feel like looking into it with what you got I would be grateful, but I understand if a test case is needed. If I can find a similar case in a public area for you to test, I'll let you know.

Btw, the _Edit_ tool you provided in the other ticket also does not scan this area.

**Comment by DanielTomberlin** [comment]
Upon further examination, I see that each time I open the window and a new div is added to the bottom of the page, the content within that div contains an **iframe**. 

![image](https://user-images.githubusercontent.com/43575829/46024014-e6e13d00-c0b3-11e8-97ef-19b19ce81cbf.png)

If I use the developer tool _Edit As Html_ on the div to copy the code I notice that it does not include anything within the iframe tag (see last image below for the expanded view of the iframe). 

![image](https://user-images.githubusercontent.com/43575829/46024238-55be9600-c0b4-11e8-9c98-8dea24435a2f.png)
![image](https://user-images.githubusercontent.com/43575829/46024374-a7ffb700-c0b4-11e8-8ee3-af83bda2d710.png)

This may not be an issue of the iframe, but that of the iframe content because it starts off like a new page. Nonetheless, this behavior with the developer tool may help understand why the extensions does not scan this area as well. 

![image](https://user-images.githubusercontent.com/43575829/46024092-0ed0a080-c0b4-11e8-92a6-8964979001eb.png)

Either way, it's more information and if anything is possible and you are willing, thanks! If not, thanks anyway.

Dan

**Comment by erosman** [comment]
Thank you. It is likely that the issue is the iframe and I have to do more testing.

If it is iframe, it can be resolved.

**Comment by CleverMuse** [comment]
Well, if you decide to make an update please comment here and I'd be happy to update the ext and test.

**Comment by CleverMuse** [comment]
Also, since both _Replace_ and _Edit_ exclude iframes, I presume IF you did resolve this it would be with both extensions. I have them both, so I'll be happy to test both... I prefer the _Edit_ you introduced me to for the copy/paste flexibility... They're both have a nice and clean design btw.

**Comment by erosman** [comment]
I have added both iframe scanning for replace and recall for the last entered values.
I am testing it at the moment and I will release an update soon after testing is done.

**Comment by erosman** [comment]
@CleverMuse I have updated the **Replace** to v1.2

**Comment by CleverMuse** [comment]
Thanks... I removed then added the extension to get the 1.2 update and noticed that values are saved upon clicking off the extension and then back on, for copy/paste flexibility, but I still get the error "_Find Pattern not found_" when I search for a term in an iframe.

**Comment by erosman** [comment]
> but I still get the error "Find Pattern not found" when I search for a term in an iframe.

I tested it with a few pages with iframes and it worked. I need a test page to find out what the problem is.

**Comment by CleverMuse** [comment]
Okay, I found a way you can access a page on the customer side of our interface that suffers the same issue as that from the staff's side. I have a test record you can login to using the credentials below:
- zzTEST@apco911.orgzz
- 123

Click on [this link](https://apconetforum.org/eweb/DynamicPage.aspx?Site=MyAPCO&WebCode=MyAPCOTaught), login, and you should be on a page that has a button labeled "Add Class Instructed" that will open up an iframe form. Type in a word in one of the form fields, then try to replace it with your extension.

Btw, I'm sorry I didn't think of this earlier as it would have been helpful to you.

**Comment by erosman** [comment]
@CleverMuse I am going to test it.. you can delete the credentials from above post if you want.

**Comment by CleverMuse** [comment]
Thanks, I did, but it's still in the "edited" area. No worries thou, I'll change the password once all is done.

**Comment by erosman** [comment]
I have testing it and it is not working on the dynamically created iframe. It works if the iframe was already there. I am looking for a solution.

**Comment by CleverMuse** [comment]
Thank you kind sir. :+1:

**Comment by erosman** [comment]
@CleverMuse Try v1.3 .. it should work now

**Comment by CleverMuse** [comment]
It works! Thank you so much! ... I'll leave that record open so you can use it to test/update the Edit ext too.

Just let me know.

**Comment by erosman** [comment]
@CleverMuse Edit also updated to v1.2 with iframe processing

**Comment by CleverMuse** [comment]
Yes, _Edit_ is also working... Thanks again!
