### ISSUE TITLE
FoxyTab: Support keyboard shortcuts

### ISSUE THREAD

**Issue by jo-so** [erosman/support#62]
Is it possible to provide shortcuts with FoxyTab?

* `Alt+Ctrl+T`: duplicate tab
* `Ctrl+x u`: copy url
* `Ctrl+x c`: copy customized
* `Ctrl+x t`: copy title

It would be great if they are customizable.

**Comment by erosman** [comment]
Firefox keyboard shortcut map is really congested. For my other other extension that require only 1 shortcut, it is hard to find a free one.

They are also rules for it
Alt+Ctrl+T is already taken by Firefox to undo close tab.
Ctrl+x u is not possible (x u etc)

ref: [Shortcut values](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values)

**Comment by willdhorn** [comment]
Would it be possible to make it so that they're unset by default, and people who want to set a custom shortcut can do so? I understand the issue of not having a free shortcut that would work well by default, but having the ability to set my own using Meh (ctrl+alt+shft) or Hyper (ctrl+alt+shft+cmd/gui) would be *incredibly* helpful.

**Comment by erosman** [comment]
There are only a few actions that can be performed from keyboard shortcuts. Most FoxyTab actions require a click to the tab to know which tab the action refers to. 

Some possibilities are: 

- Close Duplicate Tabs
- Sort Tabs
- Merge Windows

At best, keyboard short cut can only handle actions relating to the active tab.

**Comment by willdhorn** [comment]
That makes sense. I think it makes perfect sense, though, for many of the actions (were they to have a shortcut) to use the current active tab.

Personally, the biggest thing for me is being able to call "Custom Copy" for the current active tab since I have that set copy the page title and link and format it in markdown so I can easily paste it in my notes. 

And although I don't use the other actions you mentioned in my workflow, it would be a nice addition for the people that do to have (the ability to make) shortcuts for those actions.

**Comment by jo-so** [comment]
Only for the record: I'm using [Surfingkeys](https://github.com/brookhong/Surfingkeys/) to do what I've described in the request and I can redefine keys like ctrl+s. I've extended Surfingkeys to do some special copying like markdown link `[ + title + ]( + link + )` with the keys `c m`.

**Comment by erosman** [comment]
In v2.16

- Added Context-menu to Toolbar Icon
- Added Keyboard Shortcuts option
