### ISSUE TITLE
[FoxyTab] Youtube Redirect help

### ISSUE THREAD

**Issue by Mark-Decken** [erosman/support#655]
I'm trying to get the redirect feature to redirect Youtube channel home pages to Youtube channel video pages.

`https://www.youtube.com/@*		https://www.youtube.com/@$1/videos		https://www.youtube.com/@*/videos`

If I type the YT channel home page URL into the URL bar, the redirect works.

If I'm on YT and I click on a YT channel, the redirect doesn't work (I get taken to the YT channel home page).

Anyway I can fix this?

Thanks.

**Comment by erosman** [comment]
That is due to JavaScript navigation in many sites (inclining Github). It is when a website replaces the content of a page and then changes the URL in the address bar without actually navigating to the new URL.

When that happens, the browser doesn't fire the necessary event to tell extensions that the page has changed.

See also:

- https://github.com/erosman/support/issues/649#issuecomment-2276250874
- [Proposal: Trigger navigation dependent APIs on JavaScript Navigation](https://github.com/w3c/webextensions/issues/446)
- [Navigation](https://developer.mozilla.org/en-US/docs/Web/API/Navigation)
- [[meta] Implement Navigation API](https://bugzilla.mozilla.org/show_bug.cgi?id=1777171)

**Comment by Mark-Decken** [comment]
Thank you.
