### ISSUE TITLE
[Edit] - add a dark theme or give style to userContent.css / userChrome.css

### ISSUE THREAD

**Issue by wvxwxvw** [erosman/support#84]
With a dark theme, your panel looks completely unaesthetic.
Add a dark theme or give style to userContent.css / userChrome.css

**Comment by erosman** [comment]
I will try to improve it for the dark theme.

**Comment by softwarecreations** [comment]
**Please, the default theme is a killer while developing at night!**
Lots of people dark-mode all the things.

Dark Reader has almost 700K users
https://addons.mozilla.org/en-US/firefox/addon/darkreader/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

Over 3 million users on Chromium
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en

This is probably the most important, and easiest feature request.

**Comment by erosman** [comment]
OK... I will work on it.

**Comment by softwarecreations** [comment]
**Thank you very much!**

Already, 6 years ago, back in 2015 dark mode was already significantly more popular among developers than light mode https://insights.stackoverflow.com/survey/2015#tech-ide
Apparently that stat has increased from 53% (vs 40% light mode) up to 70% of developers prefering dark mode now, (but I don't know the source of that stat)
And the popularity has consistently grown since then with better tools, better OS support on desktop and mobile, and more websites supporting it natively all the time.

Dark mode is the default theme on Sublime Text

Check out these stats
    According to a recent study, 81.9% of people use dark mode on their phones.
    82.7% of survey participants said they use their operating system’s dark mode.
    64.6% of respondents expect sites to automatically apply a dark theme.
    Dark mode can reduce battery usage up to 63% on AMOLED displays.
    Adoption rates for Apple iOS dark mode are between 55–70%.

https://dev.to/surajondev/why-most-developers-prefer-the-dark-theme-ide-1ml7

https://medium.com/geekculture/4-reasons-to-adopt-the-dark-mode-in-your-app-b235632c550c

This issue likely literally affects most of the users of FireMonkey.

Thank you!!

**Comment by erosman** [comment]
> This issue likely literally affects most of the users of FireMonkey.

FireMonkey already has Dark Mode via its Themes.

**Comment by erosman** [comment]
Dark Theme is done and will be in v1.9

**Comment by erosman** [comment]
v1.9 uploaded
